### PR TITLE
php: update to 8.2.15

### LINKED ISSUE #2564: Update PHP to 8.2
#### What dependency/component is out of date?
This is not personally required, or related to a particular security issue.

I noticed that the recommended version by the Nextcloud docs was [8.2](https://docs.nextcloud.com/server/stable/admin_manual/installation/system_requirements.html) whilst doing some maintenance, although 8.1 is still acceptable.

### PR DESCRIPTION
**Pull request by kyrofa**
This PR resolves #2564 by upgrading PHP to the latest v8.2 release.

### CODE REVIEW

**Comment by kyrofa** [comment]
@Pilzinsel64 would you mind giving this a test, make sure redis works the way you expect?

**Review by Pilzinsel64 — APPROVED** [review]
Looks fine. No errors or setup check warnings regarding redis. The module is also listed in the system tab.
grafik

**Comment by kyrofa** [comment]
Excellent, thank you sir.

**Comment by pachulo** [comment]
Tested a fresh install of this and everything seems fine.

**Review by pachulo — APPROVED** [review]

**Comment by pachulo** [comment]
By they way @kyrofa : how do you update the files when we need to upgrade PHP to a new major, or minor, like this one?

**Pull request merged**
