### PR TITLE
php: enable sqlite

### PR DESCRIPTION
**Pull request by pachulo**

### CODE REVIEW

**Comment by scubamuc** [comment]
@pachulo I'd like to test this once CI is completed... any suggestions? I'll run default install and add collectives app to see if the warning comes up?

**Comment by pachulo** [comment]
Don't worry, I will test it on my instance, that is running nextcloud 28.

> I'll run default install and add collectives app to see if the warning comes up?

You can already do this using the `latest/beta` channel, since [this](https://github.com/nextcloud-snap/nextcloud-snap/pull/2795) was merged.

**Comment by scubamuc** [comment]
>You can already do that using the latest/beta channel, since https://github.com/nextcloud-snap/nextcloud-snap/pull/2795 was merged.

done

installed ccollectives app, no warning, no issues;

grafik

**Comment by scubamuc** [comment]
@pachulo 
> Did you try to create some content and search for text inside it?

nope... will try this evening

**Comment by scubamuc** [comment]
@pachulo, yeah, this works as expected:
create collective and add test
grafik

fulltest search:
grafik

collective search:
grafik

**Review by scubamuc — COMMENTED** [review]
works as expected, see tests

**Pull request merged**
