### PR TITLE
Release 25.0.9snap1

### PR DESCRIPTION
**Pull request by pachulo**
Have been running this for a week now on my production instance.

### CODE REVIEW

**Review by scubamuc — APPROVED** [review]

**Review by Pilzinsel64 — APPROVED** [review]

**Comment by pachulo** [comment]
HI @kyrofa ! How should we get this released into the `25/beta` channel?
Is it enough if I push this branch to the `25` branch of the `lp:nextcloud-snap` repo?

Thanks!

**Comment by kyrofa** [comment]
Yes, bring lp's 25 branch up to date with this one and it'll automatically build a snap for you. That will happen because [this snap build is defined](https://launchpad.net/~kyrofa/+snap/nextcloud-25) on that branch.

**Comment by pachulo** [comment]
Hi again @kyrofa ! Why is it that the snap on the `25/beta` channel is named `25.0.8snap1+git16.71a1fd3`?
I was expecting `25.0.9snap1`... 🤔

**Comment by kyrofa** [comment]
Because the snap bases its versions on git tags, which isn't something we've discussed. When you merge a release MR, you also need to take the merge commit with the new version. We'll need to tag and rebuild to get the right version there.

**Comment by pachulo** [comment]
@kyrofa should I move this to` 25/candidate` so we can then merge #2498 ?

**Comment by pachulo** [comment]
> @kyrofa should I move this to 25/candidate so we can then merge https://github.com/nextcloud-snap/nextcloud-snap/pull/2498 ?

Already did that, so that we can push 25.0.10 to beta.

**Pull request merged**
