### PR TITLE
Upgrade Nextcloud to 28.0.2

### LINKED ISSUE #2667: Upgrade Nextcloud to 28.0.2
https://nextcloud.com/changelog/

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #2667

### CODE REVIEW

**Comment by Pilzinsel64** [comment]
We need to get #2665 merged before this and a new branches "27" creased before we can merge this. See #2641 

Let us keep this open for that while. :)

**Comment by scubamuc** [comment]
Fresh install tests completed **with issues**

grafik

grafik

Version is not showing correctly!

Logs show warning and error:

grafik

[20240201-fresh-install-log.txt](https://github.com/nextcloud-snap/nextcloud-snap/files/14128237/20240201-fresh-install-log.txt)

**Comment by Pilzinsel64** [comment]
@scubamuc The version is correct, you are tracking `latest/beta` wich has 21.1.6.

**Comment by scubamuc** [comment]
My bad...

**Comment by scubamuc** [comment]
`snap install nextcloud --channel beta/pr-2668`

Fresh install retests tracking PR channel completed without issues

grafik

grafik

Logs look fine

**Comment by scubamuc** [comment]
updated [testing script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Develop-and-contribute#setup-testing-instance-per-script-optional) with maintenance setting as suggested in [wiki](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-config.php#setting-default-maintenance-window)

```
# set maintenance window
        sudo nextcloud.occ config:system:set maintenance_window_start --value="1"
```

**Review by Pilzinsel64 — APPROVED** [review]

**Pull request merged**
