### PR TITLE
Enable dailies for Nextcloud 28

### PR DESCRIPTION
**Pull request by Pilzinsel64**
- Enable dailies for Nextcloud 28, as they are already available.
- Disable dailies for Nextcloud 25, as this version is EOL.

### CODE REVIEW

**Review by scubamuc — APPROVED** [review]

**Review by pachulo — APPROVED** [review]

**Comment by Pilzinsel64** [comment]
Hm, the dailies will be uploaded to launchpad but the channel `28/edge` is not available. Do I miss something? 🤔

**Comment by Pilzinsel64** [comment]
I tested a local test-install of `28/edge`. basically everything works as expected. I also tried to update my private production isntance to `28/edge` and here too, basically it works fine. But I got around a bit trouble and finally reverted back to 27.

The issue that is relevant to snap and prevented me from keep tracking 28/edge on my private prod instance for long-term-testing were a single long-flooting issue. See this pic for the errors (recorded on the test instance).
grafik

On my private prod instance the errors has a few more such errors. That's because I have a huge number of additional apps installed.

Note: On my both other prod instances (both manually installed) this erorrs do not exists even with the same apps and versions installed.

However, I found this old issue here: https://github.com/nextcloud-snap/nextcloud-snap/issues/902
@kyrofa @pachulo What do you think? Should I open a new issue there or comment on the existing? Or is that something on our side?

**Comment by Pilzinsel64** [comment]
Also, as I read the issue above, it might not be breaking anything, or? Can I ignore that a just log-flooting bug and update again my private prod to 28/edge for futher testing until next stable release or do you recommend me to stay on 27 until we solved that issue?

**Comment by kyrofa** [comment]
We haven't changed anything in the config-- this sounds like an upstream Nextcloud issue again. I do recommend logging an issue, please.

**Comment by Pilzinsel64** [comment]
I made one, see https://github.com/nextcloud/server/issues/42671

**Comment by Pilzinsel64** [comment]
I see that also AIO stable waits for this / a similar issue: https://github.com/nextcloud/all-in-one/issues/3888 https://github.com/nextcloud/server/issues/42493

**Pull request merged**
