### PR TITLE
nextcloud: update to 24.0.8

### PR DESCRIPTION
**Pull request by pachulo**
This release includes more fixes than usual: https://github.com/nextcloud/server/milestone/208?closed=1

### CODE REVIEW

**Comment by stondino00** [comment]
Hey @kyrofa can we get this pushed to develop?  Thanks sir!

**Review by kyrofa — APPROVED** [review]

**Comment by stondino00** [comment]
Don't see this being built and available yet on the beta channel.  Thanks

**Comment by kyrofa** [comment]
Huh, what do you know. They built, but Launchpad failed to upload them and decided not to tell me about it :roll_eyes: . I just poked them.

**Comment by pachulo** [comment]
I've tried installing this from the `latest/beta` channel, but I see this error:
```
error: cannot perform the following tasks:
- Run post-refresh hook of "nextcloud" snap if present (run hook "post-refresh": Nextcloud doesn't support downgrades, but you can revert. See 'snap revert -h' for details.)
```
 So I think that you need to do what you mentioned here https://github.com/nextcloud-snap/nextcloud-snap/pull/2247#issuecomment-1356474822

**Pull request merged**
