### PR TITLE
Release 26.0.3snap1

### PR DESCRIPTION
**Pull request by Pilzinsel64**
- nextcloud: update to 26.0.3
- mdns-publisher: remove from the snap

### CODE REVIEW

**Comment by Pilzinsel64** [comment]
I hope it is ok like this. Not sure, but I remember @kyrofa said the changelog is auto-generated? If yes, just close this and do it yourself. ;) Just had that little peace of time to open such a PR without an idea what's behind the scenes regarding the release process. :P

**Comment by scubamuc** [comment]
what am I doing wrong?
tested latest/beta not getting 26.03
`sudo snap install nextcloud --channel=latest/beta`
anyway, fresh install with no issues, except the usual automatic CODE install for Nextcloud-office which needs to be removed or warned in wiki instructions?

grafik

**Comment by kyrofa** [comment]
Wow, spot on @Pilzinsel64, you're paying attention, thank you. No, the CHANGELOG isn't generated, you did seemingly exactly what I do. Sadly, however, the snap is no longer building. It's not building Launchpad either for the same reason:

```
Cloning into '/root/parts/mdns-publisher/src'...
Fetching godeps...
cannot find package "golang.org/x/tools/go/vcs" in any of:
	/snap/go/8304/src/golang.org/x/tools/go/vcs (from $GOROOT)
	/root/parts/mdns-publisher/go/src/golang.org/x/tools/go/vcs (from $GOPATH)

go get -d github.com/rogpeppe/godeps
Failed to run 'go get -d github.com/rogpeppe/godeps' for 'mdns-publisher': Exited with code 1.
Verify that the part is using the correct parameters and try again.
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
Error: Process completed with exit code 2.
```

What's happening? I'm afraid I have no idea. I actually would really like to get rid of that component entirely: I log another issue about this.

**Comment by Pilzinsel64** [comment]
@scubamuc

> what am I doing wrong?

Remind the `+gitXYZ` part behind the version number. This means that all changes up to the commit XYZ are included, so the version number is not correct, it is just like the current released state + the changes made in develop.
grafik

I'm on `latest/beta` and have exactly the version you are showing. But after a refresh, in the admin page it tells me v23.0.3.

> ... except the usual automatic CODE install for Nextcloud-office which needs to be removed or warned in wiki instructions?

I suggest to make a notice on the wiki installatin page here at the bottom or on the FAQ page: https://github.com/nextcloud-snap/nextcloud-snap/wiki/install-Nextcloud-snap
This step to install recommended apps NEVER worked for me MANUAL installation on a test server, so why should the snap package work? :D
But sure, it either has to work or should have an off-switch parameter on the `occ maintenance:install` command. I'll raise an issue on https://github.com/nextcloud/server/ later this day.

@kyrofa 

> you're paying attention, thank you

I'm glad that I can help here. But don't forget, I'm still mostly trying to find the bounds and see what I can do - of course similar to, it's your project. But also, it is a very hard step for you to give such things out of your hands. So, as long as you are fine with, that's good. If I (we) reach the edge, just tell me. ;D

**Review by scubamuc — APPROVED** [review]

**Comment by Pilzinsel64** [comment]
@kyrofa I was waiting for rebase until #2445 has been merged. Should I rebase later again or ignore it as the commit isn't required for now and keep it for the next release?

**Comment by kyrofa** [comment]
Yeah no need to include that here, we'll just include it in the next release.

**Comment by Pilzinsel64** [comment]
Yay, finally, all checks pass. :)
It's now up to you @kyrofa as `master` is protected.

**Pull request merged**
