### PR TITLE
nextcloud: include expensive steps on repair

### PR DESCRIPTION
**Pull request by Pilzinsel64**
As discusses in [#2878](https://github.com/nextcloud-snap/nextcloud-snap/issues/2878#issuecomment-2349036856)

### CODE REVIEW

**Review by scubamuc — APPROVED** [review]

**Comment by Pilzinsel64** [comment]
> Exported credentials are no longer valid for the Snap Store.

@pachulo Can you please check this when you get the chance, please?

**Comment by pachulo** [comment]
>> Exported credentials are no longer valid for the Snap Store.
>
>@pachulo Can you please check this when you get the chance, please?

It should be solved now, let's see if it's really the case.

**Comment by pachulo** [comment]
Have any of you tested this on a production instance?

**Comment by scubamuc** [comment]
@pachulo 
> Have any of you tested this on a production instance?

nope, not on production...

but fresh install tests completed without issues:
grafik

grafik

grafik

Logs look fine

**Review by pachulo — APPROVED** [review]

**Comment by pachulo** [comment]
OK, let's try this once is in the `latest/beta` channel.

**Comment by pachulo** [comment]
My bad, this PR should have been done to develop, not master @Pilzinsel64 . Sorry, I didn't notice when merging... 😢 

How can we fix the mess @kyrofa ?

**Comment by kyrofa** [comment]
I can fix master once @Pilzinsel64 proposes this to develop.

**Comment by Pilzinsel64** [comment]
Fuuu, that wasn't the plan. I usually check the banche. I hate GitHub don't take the tracking branches as default.

I restored the branche and create a new Pr right now. Sorry. :/

**Comment by pachulo** [comment]
> I can fix master once @Pilzinsel64 proposes this to develop.

Is this just a matter of reverting the commit and force-pushing @kyrofa ?

**Comment by kyrofa** [comment]
Not a revert, but a reset. It's been done.

**Pull request merged**
