### PR TITLE
nextcloud: update to 26.0.7

### LINKED ISSUE #2545: Update nextcloud to 26.0.7

### PR DESCRIPTION
**Pull request by pachulo**
Fixes #2545

### CODE REVIEW

**Comment by Pilzinsel64** [comment]
Might we need to backport the changes of @kyrofa for snap builder too?

**Review by Pilzinsel64 — APPROVED** [review]

**Comment by kyrofa** [comment]
Oh yeah, we just need to save the snap artifact (the uploader changes don't need to made here; they will always run on the master branch).

**Comment by pachulo** [comment]
Check https://github.com/nextcloud-snap/nextcloud-snap/pull/2551

**Comment by pachulo** [comment]
I've tested a fresh install and everything went smooth!

**Comment by pachulo** [comment]
Can someone else approve so this can be merged?
Thanks!

**Review by kyrofa — APPROVED** [review]

**Pull request merged**
