### PR TITLE
nextcloud: update to 27.0.1

### LINKED ISSUE #2466: Upgrade Nextcloud to 27.0.1
Url: https://download.nextcloud.com/server/releases/nextcloud-27.0.1.tar.bz2
Hash: `3976b5e8f58f934ddbeb7cc49ac33b11ad3adbd7f6d5d0908a0fc36a160c27bd`

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Fix #2466 

To be done before merging:
- [x] Release #2465
- [x] Create branche `26`

### CODE REVIEW

**Review by stondino00 — APPROVED** [review]

**Comment by Pilzinsel64** [comment]
@nextcloud-snap/developers Is [auto deploy to a temporary channel on snapcraft](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Testing-pull-requests) still a thing or is that required to be done manually? Tried to refresh for early testing but the channel can not be found.

**Comment by kyrofa** [comment]
Sadly no, but it's something we could resurrect now that GitHub Actions are the thing.

**Review by scubamuc — APPROVED** [review]

**Comment by pachulo** [comment]
Should we then create the `26` branch now @kyrofa ?

**Comment by Pilzinsel64** [comment]
> Should we then create the `26` branch now @kyrofa ?

It already is. ;)

**Comment by pachulo** [comment]
It is @Pilzinsel64 ! Thanks for the hint! :smile:

**Pull request merged**
