### PR TITLE
don't ignore `.reuse`

### LINKED ISSUE #2933: Missing `.reuse/dep5` file in Nextcloud 30 snap packages
See explanation: https://github.com/nextcloud-snap/nextcloud-snap/pull/2927#issuecomment-2422476696
See discussion at Nextcloud chat: https://cloud.nextcloud.com/call/xs25tz5y#message_3296336

- ✔️ This issue has no impact to the usage
- ✔️ This issue doesn't bring up a licensing issue

## Todo

- [x] Find the reason
- [x] PR a fix

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Fix #2933 
Required for #2927

### CODE REVIEW

**Comment by kyrofa** [comment]
Yeah this should do it, let's just confirm that it's in the resulting snap here.

**Comment by Pilzinsel64** [comment]
> just confirm that it's in the resulting snap here

... with one problem: `develop` is on NC29 which haven't the `.reuse/step5` file. I would need to checkout #2927 and build it locally with this change, but that might take a few more days. My VM seems broken and before Thursday I haven't the time to do that. The last manual build is a while back. 😄

**Comment by kyrofa** [comment]
Okay, let's temporarily add this to the other MR that DOES have it, then we can check ITS snap. If it's there, then we can last this MR and rebase that one.

**Comment by Pilzinsel64** [comment]
See #2935

**Review by kyrofa — APPROVED** [review]
+1 after #2935's testing results.

**Review by scubamuc — APPROVED** [review]

**Review by pachulo — APPROVED** [review]

**Pull request merged**
