### PR TITLE
Use cmake snap to build MySQL 8.0.37

### LINKED ISSUE #2734: MySQL starting with 8.0.37 requires cmake 3.11.2 or newer
MySQL 8.0.37 requires a newer version of cmake than what comes with core18.  Should attempt to build cmake snap or pull in from source then reference this newer version to make MySQL.

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #2734

### CODE REVIEW

**Comment by stondino00** [comment]
@kyrofa let me know if you think I did this right pulling in the cmake snap or if it's still using the default cmake from core18.  Something like this might get us by until a rebase of a newer snap core.  Thanks sir.

**Review by Pilzinsel64 — APPROVED** [review]
I thinks that absolutely fine for now, so we can  continue pushing updates. We can partly revert this after we did the core20 update.

**Comment by pachulo** [comment]
Great stuff @stondino00 ! One request though, could you clean the commit history?

**Review by scubamuc — APPROVED** [review]

**Comment by stondino00** [comment]
> Great stuff @stondino00 ! One request though, could you clean the commit history? Thanks!

How do I do this via the web on github?  I don't like to use the github desktop or cli and do all the patching commits through the web.  I'm not much of a programmer.  I can close these and make a new clean PR if that would be easier.  Thanks

**Comment by Pilzinsel64** [comment]
@stondino00 will clean it for you within the next two hours. It's the last thing I'll do before I am not at home until Sunday. ;)

**Pull request merged**
