### PR TITLE
nextcloud-fixer: flush redis DB

### LINKED ISSUE #2901: -- CLI tools, redis-cli --
@nextcloud-snap/developers 

this [here ](https://github.com/nextcloud/richdocuments/issues/3780#issuecomment-2257677440) is a possible solution for [#2798](https://github.com/nextcloud-snap/nextcloud-snap/issues/2798)

> This is caused by the cache system, I use Redis, so I had to execute FLUSHDB in redis-cli and everything work !

is `redis-cli` available somewhere as in [CLI utilities](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Included-CLI-utilities) or could this be added for maintenance in nextcloud-fixer?

maybe you have a workaround for FAQ's?

### PR DESCRIPTION
**Pull request by pachulo**
Tries to fix #2901

### CODE REVIEW

**Review by scubamuc — APPROVED** [review]

**Comment by pachulo** [comment]
@scubamuc did you test that this actually fixes the issue?

**Comment by scubamuc** [comment]
> @scubamuc did you test that this actually fixes the issue?

oops, slap my grubby fingers 😂

fresh install tests completed without issues

grafik

grafik

grafik

for the impatient among us.... `sudo snap restart nextcloud` gives the nextcloud-fixer a little push and `sudo truncate -s 0 /var/snap/nextcloud/current/logs/nextcloud.log` clears the logs...

logs look fine

**Comment by scubamuc** [comment]
CODE & Nextcloud Office works fine too...

grafik

**Review by scubamuc — APPROVED** [review]

**Comment by pachulo** [comment]
I've also checked that the command is correctly executed:
```
Oct 14 10:14:01 nextcloud-container nextcloud.nextcloud-fixer[17343]: run-parts: executing /snap/nextcloud/44641/fixes/existing-install/8_flush_redis_db.sh
Oct 14 10:14:01 nextcloud-container nextcloud.nextcloud-fixer[17924]: OK
```

**Comment by pachulo** [comment]
Can you take a look when you have time @Pilzinsel64 ? Thanks!

**Review by Pilzinsel64 — APPROVED** [review]
Seems to do its job. Nice piece of work!

**Pull request merged**
