### PR TITLE
ci: enable 27 dailies

### LINKED ISSUE #2420: Enable dailies for Nextcloud to 27
We might want a `27/edge` branche for dailies.
Tarball url: https://download.nextcloud.com/server/daily/latest-stable27.tar.bz2

- [x] [Track exists](https://forum.snapcraft.io/t/nextcloud-track-27/35624?u=kyrofa)
- [x] [Tarball exists](https://cloud.nextcloud.com/call/xs25tz5y#message_1957289)
- [x] [Make changes to `develop`](https://github.com/nextcloud-snap/nextcloud-snap/pull/2436)
- [x] Merge `develop` to `master`

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Fixes #2420 

Similar to changes by #2360. Hope that's fine.

Recommending squash and merge.

For NC24: Not sure how you handled that in past, but I suggest to keep for now as the `stable24` branche still get changes even if it's EOL (probably due enterprise).

### CODE REVIEW

**Comment by Pilzinsel64** [comment]
@kyrofa Should I target `master` directly in this case or keep going into develop?

**Comment by sakgoyal** [comment]
Can this be approved/merged soon please? I see no reason why updating this package is not just updating a couple files and merging immediately after a new release

**Review by kyrofa — APPROVED** [review]
Nice work @Pilzinsel64! This looks perfect. And no, targeting develop is almost always the right thing to do.

**Comment by kyrofa** [comment]
@Pilzinsel64 I don't generally rewrite commits made by others. If you'd like this squashed, please feel free to force-push another commit to this PR and I'll merge it.

**Comment by Pilzinsel64** [comment]
@kyrofa Not sure how to force push without closing it, maybe I am not allowed to.
But you can squash and merge on the "Mehr pull Request" drop down button.

**Comment by Pilzinsel64** [comment]
Or if someone else also wants to approve I can merge this PR myself.

**Pull request merged**
