### PR TITLE
Upgrade Apache to 2.4.58

### LINKED ISSUE #2571: Upgrade Apache to 2.4.58
Bugfixes and security fixes

https://downloads.apache.org/httpd/CHANGES_2.4.58

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #2571

### CODE REVIEW

**Review by Pilzinsel64 — APPROVED** [review]

**Comment by stondino00** [comment]
Might be an issue with how this uploaded to launchpad or something.  I'm getting this when I try and update to this build.

sudo snap refresh nextcloud --channel=latest/beta
2023-10-19T10:34:04-05:00 INFO Waiting for "snap.nextcloud.redis-server.service" to stop.
2023-10-19T10:34:06-05:00 INFO Waiting for "snap.nextcloud.mysql.service" to stop.
error: cannot perform the following tasks:
- Run post-refresh hook of "nextcloud" snap if present (run hook "post-refresh": Nextcloud doesn't support downgrades, but you can revert. See 'snap revert -h' for details.)

**Comment by pachulo** [comment]
My mistake, sorry for that!

**Comment by kyrofa** [comment]
No apology needed, thanks for all your hard work!

**Comment by stondino00** [comment]
All good guys.  Was hoping I didn't mess anything up.  I'm only good for the dependency updates :)

**Pull request merged**
