### PR TITLE
tests: support newer chrome version

### PR DESCRIPTION
**Pull request by faibz**
#2478

### CODE REVIEW

**Review by kyrofa — CHANGES_REQUESTED** [review]
Thank you, @faibz. This looks good to go, but before we ship it, would you mind bringing this branch up-to-date with develop and squashing it into a single commit, please?

**Comment by faibz** [comment]
So I guess I'm not great at the whole squashing thing. I squashed all the commits into one but that meant I had a different commit with all the develop changes (and 8 files changed), so needed to update again. Now there are 2 commits but only 4 files changed, which I think would have been the same output had I only squashed commits relevant to the issue.

Is that fine or should I do something else?

**Comment by kyrofa** [comment]
@faibz I took the liberty of squashing completely for you. Mind double-checking? Look okay?

**Comment by faibz** [comment]
Ah, you're a hero. Yeah looks good to me!

**Review by kyrofa — APPROVED** [review]

**Review by Pilzinsel64 — APPROVED** [review]

**Comment by Pilzinsel64** [comment]
@faibz Do you want to re-make the change with PR for branche `26` abd `25` too? Otherwise I would do that quickly tomorrow morning. :)

**Pull request merged**
