### PR TITLE
nextcloud: update to 27.1.9

### LINKED ISSUE #2727: Update Nextcloud to 27.1.9

### PR DESCRIPTION
**Pull request by pachulo**
Fixes #2727

### CODE REVIEW

**Comment by scubamuc** [comment]
fresh install tests completed **with** issues

grafik

grafik

add missing indexes as suggested: `sudo nextcloud.occ db:add-missing-indices`

grafik

issues resolved

grafik

logs look fine

**Comment by Pilzinsel64** [comment]
Tested myself by installing `latest/stable` and then refreshing to `latest/beta/pr-2728`. I don't have the problem with missing indices.

@scubamuc Did you wait long enought after the refresh? Ensure you see the "updated successfully" notification on web. I know the nextcloud-fixer runs a bit delayed sometimes. Nextcloud awakes from maintenance and then nextcloud-fixer runs and putting nextcloud back to maintenance mode for a minute.

**Comment by scubamuc** [comment]
@Pilzinsel64, this was a fresh install. No maintenance mode. No updated successfully message.

**Comment by Pilzinsel64** [comment]
Same goes for me with a fresh install.

**Comment by scubamuc** [comment]
retested fresh install `sudo snap install nextcloud --channel=latest/beta/pr-2731`

wait 15 Minutes...

issues persist, see messages;

grafik

**Pull request merged**
