### PR TITLE
php: enable sodium

### LINKED ISSUE #2643: [NC28] Missing recommended php module `sodium`
While testing NC28 via the `28/edge` channel Nextcloud complains about some missing PHP modules but without telling me what exactly is missing. So, let's review the installed and recommended/required php modules by following the [official documentation](https://docs.nextcloud.com/server/28/admin_manual/installation/php_configuration.html#php-modules).

### Required:
- [x] Core
- [x] ctype
- [x] curl
- [x] dom
- [x] fileinfo
- [x] filter (only on Mageia and FreeBSD)
- [x] GD
- [x] hash (only on FreeBSD)
- [x] JSON
- [x] libxml
- [x] mbstring
- [x] openssl
- [x] posix
- [x] session
- [x] SimpleXML
- [x] XMLReader
- [x] XMLWriter
- [x] zip
- [x] zlib

### Database connectors
- [x] pdo_mysql

### _Recommended_ packages
- [x] bz2 (required for extraction of apps)
- [x] intl (increases language translation performance and fixes sorting of non-ASCII characters)
- [ ] sodium (for Argon2 for password hashing. bcrypt is used as fallback, but if passwords were hashed with Argon2 already and the module is missing, your users can’t log in.)

### Required for specifc apps:
- [x] ldap (for LDAP integration)
- [ ] smbclient ([SMB/CIFS](https://docs.nextcloud.com/server/28/admin_manual/configuration_files/external_storage/smb.html) integration, see SMB/CIFS)
- [x] ftp (for FTP storage / external user authentication)
- [ ] imap (for external user authentication)
- [x] bcmath (for passwordless login)
- [ ] gmp (for passwordless login)

### Recommended for specific apps _(optional)_:
- [x] exif (for image rotation in pictures app)

### For enhanced server performance _(optional)_:
- [x] PHP module redis (>= 2.2.6, required for Transactional File Locking)

### For preview generation _(optional)_:
- [ ] imagick

### For command line processing _(optional)_:
- [x] pcntl (enables command interruption by pressing ctrl-c)

## Review

There are five modules that are "recommended" and not needed. Let's check them...
- imagick: We probably will never install this. So, ignore it.
- gmp: Might be required if someone uses passworldess login.
- imap: Might be requied if someone uses the app [External user authentication](https://apps.nextcloud.com/apps/user_external)
- smbclient: Might be required if someone wants to mount an external storage via smb.
- sodium: It's just recommended for Argon2 as an alternative to bcrypt.

## Summary

The only two modules that might be suggested by Nextcloud 28 admin overview page can be `imagick` or `sodium`. While `imagick` has its own message, the possibility is high that the meant recommended php module is `sodium`.

This said, it is probably not required to install any other module. But have you any suggestions or thoughts about installing some of the recommended apps that aren't installed yet? Should we maybe try when we finally have nc28 in stable via a PR and test its temporar channel? @nextcloud-snap/developers 

I leave this open for discussion for now. We can close it at any time and keep it as documentation or move it to a Wiki page. :)

### PR DESCRIPTION
**Pull request by Pilzinsel64**
This resolved the nice warning in NC28 by installing the php sodium extension. 

Fix #2643
Required for #2641 

grafik

It is a recommended php module by Nextcloud:
> PHP module sodium (for Argon2 for password hashing. bcrypt is used as fallback, but if passwords were hashed with Argon2 already and the module is missing, your users can’t log in.)

### CODE REVIEW

**Review by scubamuc — APPROVED** [review]

**Comment by Pilzinsel64** [comment]
Well, I tried it at least... :/
Help! 🙈

**Comment by kyrofa** [comment]
The job didn't fail, but time out. I poked it, let's see if it passes this time around. +1 to enabling this, though, thank you.

**Comment by Pilzinsel64** [comment]
> +1 to enabling this, though, thank you.

Are you saing that the implementation itself is ok? I really don't know what's the correct way. It's Try-and-error, like always. 😄

**Comment by kyrofa** [comment]
No, haha, that's why I didn't actually approve it. I'm just saying that adding PHP modules is generally contentious and we try to be judicious with it (i.e. I'm usually the dude shooting people down). In this case, I'm saying +1 to the addition of the module, given that Nextcloud itself requests it.

**Comment by Pilzinsel64** [comment]
Ah, I see. :)

**Comment by pachulo** [comment]
I think this warning tells what you are missing this @Pilzinsel64 :

> The 'php' part is missing libraries that are not included in the snap or base. They can be satisfied by adding the following entries to the existing stage-packages for this part:
> - libsodium23

**Comment by Pilzinsel64** [comment]
Thanks @pachulo!

I added that package to staging and removed the one from dev packages (hopefully this is not needed, it just was guess). I also rebased to fix the history, because I am not available today and probably tomorrow too.

If the tests are fine, it's finally ready for review! 😊

**Comment by pachulo** [comment]
Tested this on a fresh install and the `sodium` module is indeed installed:
Captura de pantalla de 2024-01-20 22-52-31

**Review by pachulo — APPROVED** [review]

**Comment by Pilzinsel64** [comment]
Thank you btw for testing! :)

**Pull request merged**
