### PR TITLE
Upgrade Nextcloud 23.0.2

### LINKED ISSUE #1999: Upgrade NextCloud 23.0.2
Released on changelog page

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #1999

### CODE REVIEW

**Comment by kyrofa** [comment]
@stondino00 I merged #1999 which conflicts with this PR, mind amending?

**Comment by kyrofa** [comment]
Builds of this PR for all architectures is available in the `latest/beta/pr-2000` channel. Please help test!

**Comment by Pilzinsel64** [comment]
Very nice! :)
Tomorrow I'll "refresh" my private (family and friends) to the beta channel and try to do the normal daily stuff with it.
(Sadly I don't have the environment to setup test VMs :( but want to help and do it like this - well, I know how to revert and have daily backups - just in case :D)

**Comment by stondino00** [comment]
Hey @kyrofa.  This PR isn't working it appears.  Something isn't right.  Snap stays on 22.2.5

error: cannot perform the following tasks:
- Run post-refresh hook of "nextcloud" snap if present (run hook "post-refresh": Nextcloud doesn't support downgrades, but you can revert. See 'snap revert -h' for details.)

**Comment by stondino00** [comment]
2022-02-17T23:28:20Z php-fpm[9520]: pool www: looking for plugins in '/usr/lib/x86_64-linux-gnu/sasl2
2022-02-17T23:28:20Z php-fpm[9520]: pool www: looking for plugins in '/usr/lib/sasl2
2022-02-17T23:29:29Z systemd[1]: Stopping Service for snap application nextcloud.apache...
2022-02-17T23:29:29Z nextcloud.apache[10694]: Certificates have been activated: using HTTPS only
2022-02-17T23:29:29Z nextcloud.apache[10694]: Certificates look to be in order: enabling HSTS
2022-02-17T23:29:29Z nextcloud.apache[10694]: HTTP compression is disabled
2022-02-17T23:29:29Z systemd[1]: Stopped Service for snap application nextcloud.apache.
2022-02-17T23:29:30Z systemd[1]: Stopping Service for snap application nextcloud.mdns-publisher...
2022-02-17T23:29:30Z systemd[1]: Stopped Service for snap application nextcloud.mdns-publisher.
2022-02-17T23:29:30Z systemd[1]: Stopping Service for snap application nextcloud.redis-server...
2022-02-17T23:29:31Z systemd[1]: Stopped Service for snap application nextcloud.redis-server.
2022-02-17T23:29:31Z systemd[1]: Stopping Service for snap application nextcloud.nextcloud-cron...
2022-02-17T23:29:31Z systemd[1]: Stopped Service for snap application nextcloud.nextcloud-cron.
2022-02-17T23:29:32Z systemd[1]: Stopping Service for snap application nextcloud.php-fpm...
2022-02-17T23:29:32Z systemd[1]: Stopped Service for snap application nextcloud.php-fpm.
2022-02-17T23:29:32Z systemd[1]: Stopping Service for snap application nextcloud.renew-certs...
2022-02-17T23:29:32Z systemd[1]: Stopped Service for snap application nextcloud.renew-certs.
2022-02-17T23:29:33Z systemd[1]: Stopping Service for snap application nextcloud.mysql...
2022-02-17T23:29:33Z nextcloud.mysql[10870]: Shutting down MySQL
2022-02-17T23:29:34Z nextcloud.mysql[10870]: . *
2022-02-17T23:29:34Z systemd[1]: Stopped Service for snap application nextcloud.mysql.
2022-02-17T23:30:10Z systemd[1]: Started Service for snap application nextcloud.mysql.
2022-02-17T23:30:10Z systemd[1]: Started Service for snap application nextcloud.mdns-publisher.
2022-02-17T23:30:10Z systemd[1]: Started Service for snap application nextcloud.renew-certs.
2022-02-17T23:30:10Z systemd[1]: Started Service for snap application nextcloud.redis-server.
2022-02-17T23:30:10Z systemd[1]: Started Service for snap application nextcloud.nextcloud-cron.
2022-02-17T23:30:10Z systemd[1]: Started Service for snap application nextcloud.php-fpm.
2022-02-17T23:30:10Z systemd[1]: Started Service for snap application nextcloud.nextcloud-fixer.
2022-02-17T23:30:10Z systemd[1]: Started Service for snap application nextcloud.apache.
2022-02-17T23:30:10Z nextcloud.nextcloud-cron[12463]: Waiting for Nextcloud config dir... done
2022-02-17T23:30:10Z nextcloud.nextcloud-fixer[12481]: Waiting for Apache...
2022-02-17T23:30:10Z nextcloud.mdns-publisher[12403]: 2022/02/17 23:30:10 Publishing files.local -> [192.168.14.20 fe80::7e4c:58ff:fe5e:a                                                                          94c] with 60-second TTL
2022-02-17T23:30:10Z nextcloud.apache[12500]: Making sure nextcloud is setup...
2022-02-17T23:30:10Z nextcloud.php-fpm[12466]: Waiting for MySQL...
2022-02-17T23:30:10Z nextcloud.apache[12500]: Waiting for PHP...
2022-02-17T23:30:12Z nextcloud.mysql[12388]: Starting MySQL
2022-02-17T23:30:14Z nextcloud.mysql[12388]: .. *
2022-02-17T23:30:14Z nextcloud.renew-certs[12414]: Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
2022-02-17T23:30:14Z nextcloud.renew-certs[12414]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2022-02-17T23:30:14Z nextcloud.renew-certs[12414]: Processing
2022-02-17T23:30:14Z nextcloud.renew-certs[12414]: /var/snap/nextcloud/current/certs/certbot/config/renewal/files.banktr.com.conf
2022-02-17T23:30:14Z nextcloud.renew-certs[12414]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2022-02-17T23:30:14Z nextcloud.renew-certs[12414]: Cert not yet due for renewal
2022-02-17T23:30:14Z nextcloud.renew-certs[12414]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2022-02-17T23:30:14Z nextcloud.renew-certs[12414]: The following certs are not due for renewal yet:
2022-02-17T23:30:14Z nextcloud.renew-certs[12414]:   /var/snap/nextcloud/current/certs/certbot/config/live/files.banktr.com/fullchain.pem                                                                           expires on 2022-04-14 (skipped)
2022-02-17T23:30:14Z nextcloud.renew-certs[12414]: No renewals were attempted.
2022-02-17T23:30:14Z nextcloud.renew-certs[12414]: No hooks were run.
2022-02-17T23:30:14Z nextcloud.renew-certs[12414]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2022-02-17T23:30:14Z nextcloud.php-fpm[12466]: done
2022-02-17T23:30:14Z nextcloud.php-fpm[12466]: Obtaining nextcloud mysql credentials... done
2022-02-17T23:30:16Z nextcloud.apache[12500]: done
2022-02-17T23:30:18Z nextcloud.apache[12500]: System config value redis => host set to string /tmp/sockets/redis.sock
2022-02-17T23:30:18Z nextcloud.apache[12500]: System config value redis => port set to integer 0
2022-02-17T23:30:19Z nextcloud.apache[12500]: System config value memcache.locking set to string \OC\Memcache\Redis
2022-02-17T23:30:20Z nextcloud.apache[12500]: System config value memcache.local set to string \OC\Memcache\Redis
2022-02-17T23:30:20Z nextcloud.apache[12500]: No such app enabled: updatenotification
2022-02-17T23:30:21Z nextcloud.apache[12500]: Making sure nextcloud is fully upgraded...
2022-02-17T23:30:21Z nextcloud.apache[12500]: Nextcloud is already latest version
2022-02-17T23:30:21Z nextcloud.apache[12500]: All set! Running httpd...
2022-02-17T23:30:21Z nextcloud.apache[12500]: Certificates have been activated: using HTTPS only
2022-02-17T23:30:21Z nextcloud.apache[12500]: Certificates look to be in order: enabling HSTS
2022-02-17T23:30:22Z nextcloud.apache[12500]: HTTP compression is disabled
2022-02-17T23:30:22Z php[13499]: looking for plugins in '/usr/lib/x86_64-linux-gnu/sasl2
2022-02-17T23:30:22Z php[13499]: looking for plugins in '/usr/lib/sasl2
2022-02-17T23:30:22Z nextcloud.nextcloud-fixer[12481]: done
2022-02-17T23:30:23Z nextcloud.nextcloud-fixer[12481]: run-parts: executing /snap/nextcloud/29572/fixes/existing-install/1_upgrade.sh
2022-02-17T23:30:23Z nextcloud.nextcloud-fixer[12481]: Nextcloud is already latest version
2022-02-17T23:30:23Z nextcloud.nextcloud-fixer[12481]: run-parts: executing /snap/nextcloud/29572/fixes/existing-install/2_update-apps.sh
2022-02-17T23:30:24Z nextcloud.nextcloud-fixer[12481]: Nextcloud is already latest version
2022-02-17T23:30:24Z nextcloud.nextcloud-fixer[12481]: run-parts: executing /snap/nextcloud/29572/fixes/existing-install/3_add-missing-in                                                                          dices.sh
2022-02-17T23:30:25Z nextcloud.nextcloud-fixer[12481]: Check indices of the share table.
2022-02-17T23:30:26Z nextcloud.nextcloud-fixer[12481]: Check indices of the filecache table.
2022-02-17T23:30:26Z nextcloud.nextcloud-fixer[12481]: Check indices of the twofactor_providers table.
2022-02-17T23:30:26Z nextcloud.nextcloud-fixer[12481]: Check indices of the login_flow_v2 table.
2022-02-17T23:30:26Z nextcloud.nextcloud-fixer[12481]: Check indices of the whats_new table.
2022-02-17T23:30:26Z nextcloud.nextcloud-fixer[12481]: Check indices of the cards table.
2022-02-17T23:30:26Z nextcloud.nextcloud-fixer[12481]: Check indices of the cards_properties table.
2022-02-17T23:30:26Z nextcloud.nextcloud-fixer[12481]: Check indices of the calendarobjects_props table.
2022-02-17T23:30:26Z nextcloud.nextcloud-fixer[12481]: Check indices of the schedulingobjects table.
2022-02-17T23:30:26Z nextcloud.nextcloud-fixer[12481]: Check indices of the oc_properties table.
2022-02-17T23:30:26Z nextcloud.nextcloud-fixer[12481]: Check indices of the oc_jobs table.
2022-02-17T23:30:26Z nextcloud.nextcloud-fixer[12481]: Done.
2022-02-17T23:30:26Z nextcloud.nextcloud-fixer[12481]: run-parts: executing /snap/nextcloud/29572/fixes/existing-install/4_add-missing-co                                                                          lumns.sh
2022-02-17T23:30:26Z nextcloud.nextcloud-fixer[12481]: Check columns of the comments table.
2022-02-17T23:30:27Z nextcloud.nextcloud-fixer[12481]: Done.
2022-02-17T23:30:27Z nextcloud.nextcloud-fixer[12481]: run-parts: executing /snap/nextcloud/29572/fixes/existing-install/5_regenerate-ass                                                                       ets.sh
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Repair MySQL collation
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - All tables already have the correct collation -> nothing to do
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Repair mime types
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Clean tags and favorites
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - 0 tags of deleted users have been removed.
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - 0 tags for delete files have been removed.
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - 0 tag entries for deleted tags have been removed.
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - 0 tags with no entries have been removed.
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Repair invalid shares
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Move .step file of updater to backup location
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Add move avatar background job
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - Repair step already executed
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Add preview cleanup background jobs
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Fix potential broken mount points
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - No mounts updated
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Repair language codes
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Install new core bundle components
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Add log rotate job
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Clear frontend caches
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - Image cache cleared
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - SCSS cache cleared
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - JS cache cleared
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Clear every generated avatar on major updates
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Add preview background cleanup job
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Queue a one-time job to cleanup old backups of the updater
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Cleanup invalid photocache files for carddav
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Add background job to cleanup login flow v2 tokens
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Remove potentially over exposing share links
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - No need to remove link shares.
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Clear access cache of projects
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Reset generated avatar flag
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Keep legacy encryption enabled
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Check encryption key format
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Remove old dashboard app config data
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Add job to cleanup the bruteforce entries
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Queue a one-time job to check for user uploaded certificates
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Repair DAV shares
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Add background job to set the lookup server share state for users
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Upgrading Circles App
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Fix component of birthday calendars
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - 0 birthday calendars updated.
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Regenerating birthday calendars to use new icons and fix old birthday events wi                                                                          thout year
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - Repair step already executed
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Fix broken values of calendar objects
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:     0 [>---------------------------]
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Registering building of calendar search index as background job
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - Repair step already executed
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Register building of social profile search index as background job
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Registering background jobs to update cache for webcal calendars
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - Added 0 background jobs to update webcal calendars
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Registering building of calendar reminder index as background job
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - Repair step already executed
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Clean up orphan event and contact data
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - 0 events without a calendar have been cleaned up
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - 0 properties without an events have been cleaned up
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - 0 changes without a calendar have been cleaned up
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - 0 cached events without a calendar subscription have been cleaned up
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - 0 changes without a calendar subscription have been cleaned up
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - 0 contacts without an addressbook have been cleaned up
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - 0 properties without a contact have been cleaned up
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - 0 changes without an addressbook have been cleaned up
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Remove activity entries of private events
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - Removed 0 activity entries
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Clean up old calendar subscriptions from deleted users that were not cleaned-up
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:     0 [->--------------------------]
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:      - 0 calendar subscriptions without an user have been cleaned up
2022-02-17T23:30:28Z nextcloud.nextcloud-fixer[12481]:  - Rebuild font library
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:  - Copy default images to the app data directory
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:      - Icon external.svg already exists
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:      - Icon external-dark.svg already exists
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:      - Icon settings.svg already exists
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:  - Fix the share type of guest shares when migrating from ownCloud
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:  - Copy the share password into the dedicated column
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:  - Set existing shares as accepted
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:  - Clean up meta table
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:  - Update OAuth token expiration times
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:  - onlyoffice
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:  - Create help command
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:  - Invalidate access cache for projects conversation provider
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:      - Invalidation not required
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:  - Cache the user display names
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:  - Add background job to check for backup codes
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:  - Insert UUIDFix background job for user and group in batches
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:  - Remove deprecated refresh time markers for LDAP user records
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]:  - Populating added database structures for workflows
2022-02-17T23:30:34Z nextcloud.nextcloud-fixer[12481]: run-parts: executing /snap/nextcloud/29572/fixes/existing-install/6_add-missing-pr                                                                          imary-keys.sh
2022-02-17T23:30:35Z nextcloud.nextcloud-fixer[12481]: Check primary keys.
2022-02-17T23:30:35Z nextcloud.nextcloud-fixer[12481]: Done.
2022-02-17T23:30:35Z nextcloud.nextcloud-fixer[12481]: run-parts: executing /snap/nextcloud/29572/fixes/existing-install/99_notify_admins                                                                          .sh
2022-02-17T23:30:35Z nextcloud.nextcloud-fixer[12481]: Enabling maintenance mode...
2022-02-17T23:30:36Z nextcloud.nextcloud-fixer[12481]: done
2022-02-17T23:30:39Z nextcloud.nextcloud-fixer[12481]: run-parts: executing /snap/nextcloud/29572/fixes/existing-install/maintenance/1_co                                                                          nvert-filecache-bigint.sh
2022-02-17T23:30:39Z nextcloud.nextcloud-fixer[12481]: Nextcloud is in maintenance mode - no apps have been loaded
2022-02-17T23:30:40Z nextcloud.nextcloud-fixer[12481]: All tables already up to date!
2022-02-17T23:30:40Z nextcloud.nextcloud-fixer[12481]: Disabling maintenance mode...
2022-02-17T23:30:41Z nextcloud.nextcloud-fixer[12481]: done

**Comment by Pride1922** [comment]
Upgrade works, no errors or problems.

Version
[Nextcloud Hub II](https://nextcloud.com/) (23.0.2)

I will edit this post in the next hours / days in case I find something wrong.

**Comment by Pilzinsel64** [comment]
Well, after a lot trouble (partly on my side and partly because snap wont start after a refresh), it worked! I'm now on 23.0.2 using the beta channel of this PR.

The only thing is, there is a message that tells me that there is a wrong reverse proxy configuration. It wasn't there before.
grafik
It navigates me to here: https://docs.nextcloud.com/server/23/admin_manual/configuration_server/reverse_proxy_configuration.html

**Comment by stondino00** [comment]
Very strange.  Never had one of these not refresh correctly to a PR.  Definitely isn't upgrading for me.

**Comment by kyrofa** [comment]
> I just rebased it I believe today so not sure if that means anything for the PR channel you created yesterday. Would that still contain 22.2.5?

> error: cannot perform the following tasks:

>    Run post-refresh hook of "nextcloud" snap if present (run hook "post-refresh": Nextcloud doesn't support downgrades, but you can revert. See 'snap revert -h' for details.)

Sorry for the delay @stondino00, don't worry, I suspect everything is as it should be! It sounds like you're following the beta channel, yes? I merged #2001, which means beta is on 22.2.5, while this PR is still based on the develop that has 22.2.3 in it. As a result, trying this PR is technically a downgrade. I'll spin new builds as soon as I can so you can ACTUALLY try it :) .

**Comment by kyrofa** [comment]
Alright @stondino00 new builds have been released into `latest/beta/pr-2000`, they should work for you now.

**Comment by kyrofa** [comment]
> Well, after a lot trouble (partly on my side and partly because snap wont start after a refresh), it worked! I'm now on 23.0.2 using the beta channel of this PR. And - as of now - no problems. If there will be anything, I will tell you here.

@Pilzinsel64 can you give me some more details about the trouble you encountered? Do you mean none of the snap services actually fired up once you upgraded? What did you need to do to get it working?

> The only thing is, there is a message that tells me that there is a wrong reverse proxy configuration. It wasn't there before.
Could that be, because I have my public IP address in "trusted_proxies" in config.php? If it is so, then it's my fault. I did that to get notify_push to work (insecure because the missing reverse proxy for it, but better then nothing).

Honestly I'm not sure, this type of thing is exactly why it's _so_ helpful to have you folks testing, thank you very much. I'll do a little bit of reading and get back to you.

**Comment by Pilzinsel64** [comment]
@kyrofa Well, after I did `sudo snap nextcloud refresh --channel=latest/beta/pr-2000` I wasn't able to access the web page. `nextcloud.occ` did work fine, but not the web page. After a long time waiting I tried to restart the snap, then the specifical the apache service, then I restarted Ubuntu. After a last `snap refresh` now I was able to access the web page. But after ~1 minute Nextcloud went to mainenance mode for a while and after it I was on NC22 (latest/stable) again, checked it with `nextcloud.occ status`.
I did a revert, then refreshes to the beta channel again and after a while waiting and a `sudo nextcloud restart nextcloud` everything worked fine.
Last night it refreshes again to it's latest version (you started a build last night) and still, everything works fine!

It's someting what I would say for: "It happened, but just forget it. Probably never happens again. Whatever it was, just a huge amount of coincidences." :D

**Comment by kyrofa** [comment]
@Pilzinsel64 any chance you looked at `snap logs nextcloud` while waiting for it to come back? It's entirely possible that it was running upgrade tasks and just took a while. One of these days I'll have the time to write some sort of "upgrade running" page that showed up during that time.

**Comment by Pilzinsel64** [comment]
@kyrofa Sorry now. Didn't know that command. :/ But for sure, I'll remember and next time I will use it. ;)
Because that time it takes for the upgrade, I waited about half a hour until I tried to start/restart the snap. And normally it takes never soo long. 10 to 15 minutes was the highest waiting time in the past.

**Comment by aniketfuryrocks** [comment]
after refreshing using
```bash
sudo snap refresh --channel=latest/beta/pr-2000
```

*I get the following logs*
```bash
$ sudo snap logs nextcloud
2022-03-05T11:06:27Z nextcloud.php-fpm[152007]: Obtaining nextcloud mysql credentials... done
2022-03-05T11:06:27Z nextcloud.renew-certs[152158]: Cert not yet due for renewal
2022-03-05T11:06:27Z nextcloud.renew-certs[152158]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2022-03-05T11:06:27Z nextcloud.renew-certs[152158]: The following certs are not due for renewal yet:
2022-03-05T11:06:27Z nextcloud.renew-certs[152158]:   /var/snap/nextcloud/current/certs/certbot/config/live/nextcloud.aniketprajapati.me/fullchain.pem expires on 2022-06-03 (skipped)
2022-03-05T11:06:27Z nextcloud.renew-certs[152158]: No renewals were attempted.
2022-03-05T11:06:27Z nextcloud.renew-certs[152158]: No hooks were run.
2022-03-05T11:06:27Z nextcloud.renew-certs[152158]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2022-03-05T11:06:28Z nextcloud.nextcloud-cron[152364]: Nextcloud is in maintenance mode, hence the database isn't accessible.
2022-03-05T11:06:28Z nextcloud.nextcloud-cron[152364]: Cannot perform any command except 'maintenance:mode --off'
```

I get a maintenance mode screen, which I am able to bypass using

```bash
sudo nextcloud.occ maintenance:mode --off
```

**Comment by kyrofa** [comment]
@aniketfuryrocks how long did you wait? The snap will throw itself into maintenance mode and take of running all the updates etc. (including the indices), but it can take a few minutes. Your log only shows cron output, so it's not clear if the update technically finished and left itself in a weird state, or if it was in the middle when you took it out of maintenance mode. `snap logs <snap name>` interleaves output from all services from that snap. When monitoring an upgrade, that method is the easiest, but not foolproof unless you tail it and watch it for a while. I actually [wrote up a quick post](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Monitor-an-upgrade) outlining how to fully monitor an upgrade, if it's helpful.

**Comment by Bobmorton-TX** [comment]
I am using --channel=latest/beta/pr-2000 and managed to transfer database and data from regular NC install.
all worked except Nextoffice using the CODE server.
accessing it from my.ddns.net adress failed (Nextcloud office failed to load). using the server name (BERRY2000) or its IP worked.
I added 127.0.0.1 my.ddns.net to /etc/hosts. now it works.
I am not sure if this is expected behavior or any issue with this build. 
(please excuse me if this does not belong here at all)

**Comment by bentwnghk** [comment]
I have successfully migrated to NextCloud 23.0.2 using the latest/beta/pr-2000 channel.
Everything is working as it should, except for the following warning from the Admin Overview page:

> The PHP OPcache module is not properly configured:
> The OPcache interned strings buffer is nearly full. To assure that repeating strings can be effectively cached, it is recommended to apply opcache.interned_strings_buffer to your PHP configuration with a value higher than 8.

Though I may be wrong, my initial guess is that the RSS feeds I am subscribing to through the News app are utilizing a large amount of cache, and it is simply a coincidence that the threshold was (about to be) crossed by the time I did my migration to NextCloud 23.0.2.

Would be grateful if some of the more technical guys here could explain what I could do to get rid of this warning.

**Comment by Bobmorton-TX** [comment]
after install I had the same message which has now disappearded after abit of use
> 
> > The PHP OPcache module is not properly configured:
> > The OPcache interned strings buffer is nearly full. To assure that repeating strings can be effectively cached, it is recommended to apply opcache.interned_strings_buffer to your PHP configuration with a value higher than 8.

**Comment by kyrofa** [comment]
Great feedback, thank you @bentwnghk! The default configuration for opcache is to save 8 MB for string storage in the cache. Some usages will end up utilizing that 8 MB more heavily than others, and Nextcloud will point it out as of 23.0.1 I believe. It's not an error, in the end it's just a cache. If it becomes full, PHP has to start throwing things out instead of remembering them. If you see this warning regularly, it implies that you might have slightly better performance by increasing the cache size. If you do indeed see this regularly, log a separate issue. We can make it configurable.

**Comment by bentwnghk** [comment]
@Bobmorton-TX Thanks for sharing your experience!
@kyrofa Thanks for your reassurance! Will keep an eye out for the warning in a couple weeks' time and report back.

**Review by kyrofa — APPROVED** [review]
Alright, after getting some feedback (thank you all!) and testing this myself as a fresh install and an upgrade, I think we're ready for it.

**Pull request merged**
