### PR TITLE
php: enable sqlite3 & pdo-sqlite

### LINKED ISSUE #2744: Include PDO SQLite driver (Collectives)
A few apps (e.g. like Collectives and a AI app I forgot yet) requires PDO SQLite driver for some features.

Ref: https://nextcloud.github.io/collectives/administration/#searching-collectives

At the moment you either live with red error texts at the Overview page or don't use the app in question at all or you need to switch to AIO docker container.

This line seems to exclude it at the moment:
https://github.com/nextcloud-snap/nextcloud-snap/blob/357ee46c68d34a04b36a421ff1ada2ece5e43a15/snap/snapcraft.yaml#L239

We already had [similar requests](https://github.com/nextcloud-snap/nextcloud-snap/issues/2555), but I tread this different as SQLite commonly used for app data and not for productive use.

What do you think? @nextcloud-snap/developers

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Fix #2744

Need to be tested, not sure if we need to enable something explicitely or if its enough to remove the disable lines.

### CODE REVIEW

**Review by scubamuc — APPROVED** [review]

**Comment by pachulo** [comment]
I was taking a look at this today. 

> Need to be tested, not sure if we need to enable something explicitely or if its enough to remove the disable lines.

Besides that we are gonna need, at least, some library for building it and maybe some more for runtime, but I still don't know which ones.

**Comment by Pilzinsel64** [comment]
@pachulo ah, I see. If you want, feel free to take over, if you find a solution. I probably have no time until Tuesday to actively work on this. Only spontaneous. 

(Sorry btw that I am so busy at the moment. It will be better again soon probably.)

**Comment by pachulo** [comment]
OK, this built and passed CI, now it's time to see if it really solves the problems with the Apps.

**Comment by scubamuc** [comment]
fresh install tests completed without issues

grafik

grafik

## test for PDO SQLite

prepare test instance, clear logs
install missing indices for `mail`
check logs for new entries `sudo nextcloud.occ log:watch`
clear logs `sudo truncate -s 0 /var/snap/nextcloud/current/logs/nextcloud.log`

install app `fulltextsearch` 
check logs
grafik
configure app as described: _failed (Hyperlink to missing description) (missing documentation)_
grafik
leave unconfigured

install app `collectives`
install completed without issues
check logs for new entries: **no new entries**
check overview admin section for PDO SQLite red warning: **no warning**

check basic settings admin section whether cron is failing: cron running fine **without errors** 

well done, looking good "enable sqlite3 & pdo-sqlite" testing complete and sucessful

**Comment by scubamuc** [comment]
@pachulo, docs are suggesting a host service to configure `fulltextsearch` core app. 
host service as suggested by app-devs will probably not work due to snap-confinement! 
do you have any ideas how we could preconfigure `fulltextsearch`?
assuming unconfigured core app will suffice.

**Review by scubamuc — APPROVED** [review]
👍 testing completed

**Comment by pachulo** [comment]
Thanks for taking a look and testing @scubamuc !

> @pachulo, docs are suggesting a host service to configure fulltextsearch core app.
host service as suggested by app-devs will probably not work due to snap-confinement!
do you have any ideas how we could preconfigure fulltextsearch core app?
assuming unconfigured core app will suffice.

I think that we should discuss that in another bug/PR: let's focus on how to add the PHP extensions in this one.

**Comment by scubamuc** [comment]
Hi @pachulo,

this PR corrects `fulltextsearch` issues appearing since upgrade to v28 and v29: 

- #2793
- #2787
- #2780
- #2758
- #2744

**Comment by scubamuc** [comment]
@pachulo 

>My question here would be: does this PR fix some error on applications other than Collectives?

More important, this PR fixes cron going away due to `fulltestsearch` requirement.

**Comment by pachulo** [comment]
Thanks for the links @scubamuc ! But, as far as I understood, this will _only_ solve the problem that content created with the `Collectives` app won't be available for full text search, if `fulltextseach` app is also installed, of course, isn't it?

I mean, maybe that's enough of a use case (I don't really know how popular that `Collectives` app is) but I just want to make explicit that I still didn't find any evidence that this would be necessary for other applications.

**Comment by scubamuc** [comment]
@pachulo I may be grabbing for straws, but there are so many issues concerning `fulltextsearch` that I'm not even sure myself, if this PR fixes it or not.  
Even cron crashed again on the 29.02.01 testing system after 24 hours!
so I'm not sure any more if this PR fixes anything apart from the red warning for `collectives`... maybe @Pilzinsel64 can shed some light when he gets around to testing this?
I'm sorry for any inconvenience.

**Comment by scubamuc** [comment]
@pachulo 
>I mean, maybe that's enough of a use case (I don't really know how popular that Collectives app is) but I just want to make explicit that I still didn't find any evidence that this would be necessary for other applications.

I agree fully with you. I checked and could not find any evidence that this is necessary for any other applications other than "collectives" #2787. I obviously misunderstood the relevance for "FTS" #2787 and "cron" #2793 completely.

>I don't really know how popular that Collectives app is

we use it in our corporate instance and judging by @Pilzinsel64 issue request https://github.com/nextcloud-snap/nextcloud-snap/issues/2744 there have been some requests for integration.  But these apps added in my comment https://github.com/nextcloud-snap/nextcloud-snap/issues/2744#issuecomment-2172845984 were an error on my side mentioned here https://github.com/nextcloud-snap/nextcloud-snap/issues/2744#issuecomment-2184025770. Once again, sorry for the misunderstanding an inconvenience.

**Review by scubamuc — APPROVED** [review]

**Comment by pachulo** [comment]
@Pilzinsel64 can you modify this so that it's only 1 commit?

**Comment by Pilzinsel64** [comment]
Done!

**Review by pachulo — APPROVED** [review]

**Pull request merged**
