### PR TITLE
Upgrade Nextcloud to 29.0.5

### LINKED ISSUE #2853: Upgrade Nextcloud to 29.0.5
https://github.com/nextcloud/server/releases/tag/v29.0.5

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #2853

### CODE REVIEW

**Review by Pilzinsel64 — APPROVED** [review]

**Review by scubamuc — APPROVED** [review]

**Comment by pachulo** [comment]
First of all, thanks a lot for all the tests and the effort @scubamuc !

Regarding:
> known issues upstream:
> 
> * https://github.com/nextcloud/server/issues/47359
> see also [Mimetype Warning after upgrading to 28.0.9 or 29.0.5](https://help.nextcloud.com/t/mimetype-warning-after-upgrading-to-28-0-9-or-29-0-5/201289)
> 
> * https://github.com/nextcloud/richdocuments/issues/3912

I've been reading about the issues and I'm of the opinion that we can push this to the stable channel, as they don't seem critical and the next version is planned for the 12th of September and there are many fixes on it.

What do you think @nextcloud-snap/developers ?

**Comment by Pilzinsel64** [comment]
Yea, I agree with @pachulo :)

**Comment by Pilzinsel64** [comment]
Uff, completely missed creating a release PR. Doing that tomorrow morning after stand-up. It's a week now and I am having no new issues. JFYI

**Comment by pachulo** [comment]
It seems like [they will be doing an out of bound release in 3 days](https://help.nextcloud.com/t/rc1-of-29-0-6-available/202059) that includes a fix for [one of the issues](https://github.com/nextcloud/server/issues/47359), is maybe worth waiting then?

**Comment by Pilzinsel64** [comment]
Oh dear, If I would just have looked to this comment few minutes earlier before creating this #2866  ... 😄
But yes, I agree, it wouldn't hurt at all to just wait for it and *then* publish a new release. 🙂

**Comment by scubamuc** [comment]
@Pilzinsel64, should I test #2866 anyway?

**Pull request merged**
