### PR TITLE
apache: enable `application/javascript` mimetype

### LINKED ISSUE #2656: [NC28] Missing `application/javascript` mimetype
Nextcloud 28 complains about missing Javascript mimetype. We should fix that before releasing NC28 packages.
grafik

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Fix #2656
Required for #2641 

Maybe also fix the ResourceLoader webroot issue! Need to be tested when dailies have this fix included.

### CODE REVIEW

**Comment by Pilzinsel64** [comment]
It's so sad, this change needs to go to master until I can verify if it's working. Same for #2655

**Review by scubamuc — APPROVED** [review]

**Comment by kyrofa** [comment]
Yes, it appears that apache ships its own:

> Failed to stage: Parts 'apache' and 'apache-customizations' have the following files, but with different contents:
>     conf/mime.types

**Comment by Pilzinsel64** [comment]
Do you know any way to pass this? Maybe without coding?
This change seems to be important for NC28+.

**Comment by kyrofa** [comment]
Not off the top of my head. We could always patch that file when building Apache if we need to.

**Comment by Pilzinsel64** [comment]
Oh dear, we probably don't need this. See https://github.com/nextcloud/server/issues/42989 Fix in https://github.com/nextcloud/server/pull/42999

When I tested nc28 on my prod instance two weeks back I didn't have this error. Also when I write the hostname to the config, it works. I am also able to download the file `https://ncsnaptest/apps/settings/js/esm-test.mjs` as `text/javascript`.

grafik

**Pull request closed without merging**
