### PR TITLE
Revert "mysql: revert BUG#34849343 Aligned_atomic not working as intended"

### PR DESCRIPTION
**Pull request by pachulo**
MySQL 8.0.35 contains the proper fix for https://bugs.mysql.com/bug.php?id=110752. Check https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-35.html:

> On EL7 aarch64-based platforms, fixed an issue related to how fetching the CPU cache line size returned 0 that caused the MySQL server to unexpectedly halt. (Bug #110752, Bug #35479763)

We should build this for arm64, because the issue only affects that arch.

This reverts commit 4f2d421c19857460f266fc3c27ebbe47ca096481.

### CODE REVIEW

**Comment by kyrofa** [comment]
> We should build this for arm64, because the issue only affects that arch.

Building for all architectures now. By the way, that just looks something like this:

    $ snapcraft remote-build && for f in *.snap; do snapcraft upload "$f" --release=latest/beta/pr-2592; done

**Comment by pachulo** [comment]
@jdstrand @dasaweb @jkimsis could you try refreshing to this branch (`latest/beta/pr-2592`) and then check if mysql starts OK and everything else works as it should?

Thanks a lot!

**Comment by jkimsis** [comment]
> @jdstrand @dasaweb @jkimsis could you try refreshing to this branch (`latest/beta/pr-2592`) and then check if mysql starts OK and everything else works as it should?
> 
> Thanks a lot!

Hey, I updated to the latest stable branch (27.1.1snap1) when it came out and it's working fine.

**Comment by pachulo** [comment]
> Hey, I updated to the latest stable branch (27.1.1snap1) when it came out and it's working fine.

Yes, that's to be expected, as it includes the patch reverting the problem we found with MySQL on arm64 systems, but this branch gets rid of that patch and used vainilla MySQL 8.0.35, which should contain a proper fix, that's why we are asking for you to test after a refresh to `latest/beta/pr-2592`

Thanks again!

**Comment by jdstrand** [comment]
```
# per the other issue, I used former latest/beta/pr-2509 (worked), then upgraded
# through 25/stable, 26/stable to end up on latest/stable
$ snap list nextcloud
nextcloud          27.1.1snap1             37742  latest/stable     nextcloud✓  -

$ sudo snap refresh nextcloud --channel=latest/beta/pr-2509
Download snap "nextcloud" (38412) from channel "latest/beta/pr-2509"                                              100% 1.29MB/s 0.0ns
2023-10-31T07:33:26-05:00 INFO Waiting for "snap.nextcloud.redis-server.service" to stop.
2023-10-31T07:33:27-05:00 INFO Waiting for "snap.nextcloud.apache.service" to stop.
2023-10-31T07:33:32-05:00 INFO Waiting for "snap.nextcloud.mysql.service" to stop.
nextcloud (beta) 27.1.2snap1+git9.1d25a28 from Nextcloud✓ refreshed

$ snap list nextcloud
Name       Version                   Rev    Tracking       Publisher   Notes
nextcloud  27.1.2snap1+git9.1d25a28  38412  latest/beta/…  nextcloud✓  -
```

It seems to be running fine after refreshing.

**Comment by dasaweb** [comment]
> @jdstrand @dasaweb @jkimsis could you try refreshing to this branch (`latest/beta/pr-2592`) and then check if mysql starts OK and everything else works as it should?

I'm on the road and can't (or "don't want" to be more precisely) test this until next week at the earliest, sorry...

**Review by kyrofa — APPROVED** [review]
I'm personally comfortable shipping this with just @jdstrand's test.

**Comment by jkimsis** [comment]
> > Hey, I updated to the latest stable branch (27.1.1snap1) when it came out and it's working fine.
> 
> Yes, that's to be expected, as it includes the patch reverting the problem we found with MySQL on arm64 systems. But this branch gets rid of that patch and uses vanilla MySQL 8.0.35, which should contain a proper fix, that's why we are asking for you to test after a refresh to `latest/beta/pr-2592`
> 
> Thanks again!

```
$ sudo snap refresh nextcloud --channel=latest/beta/pr-2509
2023-10-31T23:16:45+02:00 INFO Waiting for "snap.nextcloud.mysql.service" to stop.
2023-10-31T23:16:52+02:00 INFO Waiting for "snap.nextcloud.apache.service" to stop.
nextcloud (beta) 27.1.2snap1+git9.1d25a28 from Nextcloud✓ refreshed
$ sudo snap list nextcloud
Name       Version                   Rev    Tracking       Publisher   Notes
nextcloud  27.1.2snap1+git9.1d25a28  38412  latest/beta/…  nextcloud✓  -
```

I've updated to latest/beta/pr-2509and after restarting the server it seems to be working fine.

**Review by Pilzinsel64 — APPROVED** [review]

**Comment by Pilzinsel64** [comment]
I have several arm64 devices myself but currently no one ready to test this on yet. I moved my prod instanced to x64 several month ago (the laptop has much more performance then my pi4).

**Pull request merged**
