### PR TITLE
Update Nextcloud to 27.1.1

### LINKED ISSUE #2534: Update Nextcloud to 27.1.1
What's Changed

    [stable27] fix(mimetype): Fix aborted transaction on PostgreSQL when storing mimetype by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/40461
    [stable27] Backport consider link shares in removeShare method in SharingTab https://github.com/nextcloud/server/pull/40440 by @Fenn-CS in https://github.com/nextcloud/server/pull/40448
    [stable27] don't preload metadata for the sub-childen by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/40473
    [stable27] fix: don't use davtags for tag search by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/40444
    [stable27] fix: use faster method to fetch user count by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/40433
    [stable27] SFTP improvements by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/40487
    [stable27] fix(comments): Use provided offset in best effort when loading comments by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/40506
    [stable27] Fix alignments for share different share entry types. by @Fenn-CS in https://github.com/nextcloud/server/pull/40429
    [stable27] fix: content info footer on guest pages by @st3iny in https://github.com/nextcloud/server/pull/40520
    [stable27] Consider share type for enforced share expiry dates by @Fenn-CS in https://github.com/nextcloud/server/pull/40530
    [stable27] Auto set password for new email shares by @Fenn-CS in https://github.com/nextcloud/server/pull/40535
    [stable27] Fix issues where unencrypted_size was being falsely used for non-encrypted home folders by @juliushaertl in https://github.com/nextcloud/server/pull/40379
    27.1.1 by @blizzz in https://github.com/nextcloud/server/pull/40525

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #2534

### CODE REVIEW

**Review by Pilzinsel64 — APPROVED** [review]

**Comment by kyrofa** [comment]
Hey guys, if we can continue using our forks for our invidual development instead of pushing a branch directly to this repo, we can avoid the duplicate CI jobs (notice that we're running CI on push as well as pull request, thus this one gets both). No need to change this one, just something to keep in mind for the future.

**Comment by scubamuc** [comment]
Hey guys,

fresh install tests completed `--channel=latest/beta` without issues.

grafik

grafik

**Comment by Pilzinsel64** [comment]
An update on my private instance from v27.1 went smoothly. Everything seems to work as expected.

**Comment by scubamuc** [comment]
Hey guys... sorry about the late feedback.

I usually run the "issue debug script" against fresh install tests immediately. This time I was a bit too slow I guess.

Log -- nextcloud-fixer error found:
grafik

```
│Sep 23 14:13:48 NC-SNAP--testing nextcloud.nextcloud-fixer[25122]: run-parts: executing /snap/nextcloud/37723/fixes/fresh-install/1_disable-theming.sh                                                     │
│Sep 23 14:13:48 NC-SNAP--testing nextcloud.nextcloud-fixer[25123]: Disabling theming by default...                                                                                                         │
│Sep 23 14:13:48 NC-SNAP--testing nextcloud.nextcloud-fixer[25123]: error                                                                                                                                   │
│Sep 23 14:13:48 NC-SNAP--testing nextcloud.nextcloud-fixer[25123]: theming can't be disabled. 
```
I believe this issue has to do with: #2456
We should remove this from "fixer"?

**Pull request merged**
