### PR TITLE
php: update to 8.2.14

### LINKED ISSUE #2564: Update PHP to 8.2
#### What dependency/component is out of date?
This is not personally required, or related to a particular security issue.

I noticed that the recommended version by the Nextcloud docs was [8.2](https://docs.nextcloud.com/server/stable/admin_manual/installation/system_requirements.html) whilst doing some maintenance, although 8.1 is still acceptable.

### PR DESCRIPTION
**Pull request by Pilzinsel64**
fix #2564

### CODE REVIEW

**Review by scubamuc — APPROVED** [review]

**Comment by Pilzinsel64** [comment]
I don't really like that missing redis extension: https://stackoverflow.com/questions/76561932/why-is-the-redis-extension-not-working-with-php-8-2

**Comment by pachulo** [comment]
Hi @Pilzinsel64 ! I think you need to update more things, apart from the snapcraft.yml.
Check the [last PR with an upgraded branch of PHP from](https://github.com/nextcloud-snap/nextcloud-snap/pull/2318) @kyrofa

**Comment by Pilzinsel64** [comment]
Alright, so I'll close this for now. I have no idea what's up with that redis module and I would need a lot try-and-error (and time) to find it out. Probably @kyrofa knows what to do, so I'll let this up for him. :)

**Comment by kyrofa** [comment]
Given that we build the redis extension from scratch, that may not actually be a problem @Pilzinsel64. As the others have said though, when bumping PHP's minor version, there are other changes you need to make, or PHP won't run. That's your problem at this point anyway. If we get that config proper, then we can see if the redis extension has issues or not.

**Comment by kyrofa** [comment]
Took my own crack at this in #2654.

**Pull request closed without merging**
