### PR TITLE
Upgrade Nextcloud to 24.0.7

### LINKED ISSUE #2223: Upgrade Nextcloud to 24.0.7
Contains bugfixes

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #2223

### CODE REVIEW

**Comment by stondino00** [comment]
They've posted to the blog about this release being available now.

**Review by kyrofa — APPROVED** [review]

**Comment by pachulo** [comment]
Hi @kyrofa ! Is there any ETA for promoting this to `24/stable`?
Thanks!

**Comment by pachulo** [comment]
Hi again @kyrofa ! New point releases are coming next week, so I was wondering if there's any problem stopping this release and the 23.0.11 one from hitting the respective stable channels?
Thanks!

**Comment by kyrofa** [comment]
Hey @pachulo, thanks for the ping! Done and done.

**Pull request merged**
