### PR TITLE
nextcloud: update to 27.1.2

### LINKED ISSUE #2559: Update nextcloud to 27.1.2
https://nextcloud.com/changelog/

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Fix #2559

### CODE REVIEW

**Review by stondino00 — APPROVED** [review]

**Comment by stondino00** [comment]
This is failing to build in launchpad it appears @kyrofa . Thanks

**Comment by pachulo** [comment]
I've just relaunched the builds that failed (armhf was succesful)

**Comment by pachulo** [comment]
I don't know what's going on, arm64 build is failing with this error:

```
Running repo phase...
Cloning into 'nextcloud'...
fatal: unable to access 'https://git.launchpad.net/nextcloud-snap/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
Build failed
```
The rest of the builds went OK and are on the `latest/beta` channel.
I've tried to rebuild it a few time now...any ideas @kyrofa ?

**Comment by Pilzinsel64** [comment]
But the build on PF went fine, why? 🤔

**Comment by kyrofa** [comment]
Looks like a temporary outage is all. Builds look green again.

**Comment by scubamuc** [comment]
@Pilzinsel64 i'll need the machine for testing fresh install... are you finished there? may I kill your install?

**Comment by Pilzinsel64** [comment]
@scubamuc Of course, feel free.

**Comment by scubamuc** [comment]
Fresh install tests completed without issues:

grafik

grafik

**Comment by scubamuc** [comment]
The Logs for `latest/beta` are showing the FQDN-warning again after fresh install. @Pilzinsel64, so we were mistaken thinking that this was gone since mDNS was removed. We'll need to figure out "setting FQDN" vs. "CODE and Office" `/etc/hosts`using localhost only:

```
Oct 09 13:50:58 NC-SNAP--testing nextcloud.apache[286960]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 192.168.2.222. Set the 'ServerName' directive globally to suppress this message
```
@kyrofa, do you know another method to set the 'ServerName' directive other that `/etc/hosts`. I was thinking along the lines of `hostnamectl`, but the is no Option for the FQDN. According to [this](https://yewtu.be/watch?v=bA8GVdGFT30) setting FQDN is "best practice".

**Comment by Pilzinsel64** [comment]
The only important thing to add:
The nextcloud server needs to be able to make https requests to it's FQDN, so it need to go throw the proxy server. This is how nextcould want to work.
Editing the hosts file does work if the nextckoud server also handles https. But if it doesn't because there is another server as proxy between, then there is another way needed I guess.

**Comment by Pilzinsel64** [comment]
The only important thing to add:
The nextcloud server needs to be able to make https requests to it's FQDN, so it need to go throw the proxy server. This is how nextcould want to work.
Editing the hosts file does work if the nextckoud server also handles https. But if it doesn't because there is another server as proxy between, then there is another way needed I guess.

I have read that some people said adding "ServerName localhost" to https.conf would be enough. 🤔 

@scubamuc Isn't 192.168.2.222 your proxy? Did you try adding an A record to your DNS (if you have one) with your FQDN and the IP of your proxy as destination? Or as alternative, you can try adding an entry to the /etc/hosts file to your nextckoud server with the IP of your proxy and the FQDN.

**Comment by scubamuc** [comment]
@Pilzinsel64 thanks for pointing that out. nope x.x.x.222 is not my proxy, but I've added:
```
<x.x.x.ProxyIP> <my.sexy.domain.io> <servername>
```
to `/etc/hosts` and FQDN warning has disappeared.

Do you think I should add that to Wiki?

**Pull request merged**
