### PR TITLE
Release 30.0.2snap2

### PR DESCRIPTION
**Pull request by pachulo**

### CODE REVIEW

**Review by Pilzinsel64 — APPROVED** [review]
Works fine on my private prod.

**Comment by scubamuc** [comment]
> Works fine on my private prod.

hmmm.. Snap Publisher -- Snap failed to upload/release ?

**Comment by pachulo** [comment]
>> Works fine on my private prod.

>hmmm.. Snap Publisher -- Snap failed to upload/release ?

I think that @Pilzinsel64 refers to the version that is currently on `latest/beta/pr-2973` channel

**Comment by Pilzinsel64** [comment]
> I think that @Pilzinsel64 refers to the version that is currently on `latest/beta/pr-2973` channel

Oh, no. I mean `latest/beta`. Falsely thought I got an update message few days ago and assumed this is just the release for it. Sorry, my mistake. Missed that `latest/beta` isn't up-to-date.

**Review by stondino00 — APPROVED** [review]

**Review by scubamuc — APPROVED** [review]

**Pull request merged**
