### PR TITLE
Release 27.1.0snap1

### PR DESCRIPTION
**Pull request by kyrofa**
- mysql: revert BUG#34849343 Aligned_atomic not working as intended
- nextcloud: update to 27.1.0

### CODE REVIEW

**Review by pachulo — APPROVED** [review]

**Review by Pilzinsel64 — APPROVED** [review]

**Comment by stondino00** [comment]
Maybe hold off on this @kyrofa .  Looks like they are releasing a 27.1.1 to fix a few bugs that were found in 27.1.0.  I'm making the issue and PR now.

**Comment by kyrofa** [comment]
Thank you @stondino00, standing by.

**Comment by Pilzinsel64** [comment]
Hm, interesting, I didn't know they also releasing a new version for 27 as 27.1 is fine. 🤔  The bug they wanted to htofix primary is for 26 and 25, just to fix the updater won't start due the new four files they ship with that versions. For 27 it was only while the RC phase but fixed in stable already.
At least my knowledge from, yetserday morning.

Anyway looks like one or two longer present bugs has been fixed now in 21.1.1. At least something. :)

**Comment by Pilzinsel64** [comment]
See https://help.nextcloud.com/t/third-rc-of-nextcloud-27-1-0/169961/18?u=pilzinsel64

**Comment by kyrofa** [comment]
Superseded by #2537.

**Pull request closed without merging**
