### PR TITLE
nextcloud: update to 23.0.9

### LINKED ISSUE #2173: Upgrade Nextcloud to 23.0.9

### PR DESCRIPTION
**Pull request by pachulo**
Fixes #2173

### CODE REVIEW

**Comment by pachulo** [comment]
I will test this as soon as it lands on the `23/beta` channel @kyrofa

**Review by kyrofa — APPROVED** [review]

**Comment by pachulo** [comment]
I've updated my instance with the latest build on `23/beta` and now everything looks broken in the Web UI:
image

In Chrome's console I can see a lot of error messages like this:
```
Refused to apply style from 'https://X.Y/index.php/css/core/4151-4dbf-css-variables.css?v=d41d8cd98f00b204e9800998ecf8427e-95353a04' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

I've tried to use Firefox with the same result and this messages:
```
The resource from “https://X.Y/index.php/css/core/4151-4dbf-css-variables.css?v=d41d8cd98f00b204e9800998ecf8427e-95353a04” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

Is this some upstream bug?

**Comment by pachulo** [comment]
OK, tested this again and everything looks fine.

**Comment by kyrofa** [comment]
Thanks @pachulo. Sorry for the delay, I was on vacation for a bit. Keep an eye on #2184.

**Pull request merged**
