### PR TITLE
Enable Dependabot version update for actions

### PR DESCRIPTION
**Pull request by pachulo**
I think this is worth it, what do you think @kyrofa ?

### CODE REVIEW

**Comment by pachulo** [comment]
Can I go on with this @kyrofa ?

**Comment by kyrofa** [comment]
Your call @pachulo, I have no informed opinion on this.

**Comment by pachulo** [comment]
Well, I missed this one: this is opening the PRs against our default branch, `master`, but I'm of the opinion that we should [configure it](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch) to open them on `develop`. Do you agree @kyrofa ?

**Comment by kyrofa** [comment]
Yes, agreed.

**Pull request merged**
