### PR TITLE
nextcloud: update to 26.0.5

### LINKED ISSUE #2495: Update Nextcloud to 26.0.5
Url: https://download.nextcloud.com/server/releases/nextcloud-26.0.5.tar.bz2
Hash: `9e1ab46806384f585465d28963ae994a58ab09280f41eb7c609a5c8b0270d5be`

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Fix #2495

### CODE REVIEW

**Review by scubamuc — APPROVED** [review]

**Comment by scubamuc** [comment]
Fresh install tests completed without issues:

grafik

grafik

**Comment by pachulo** [comment]
Are you sure you tested the right version @scubamuc ? In your last picture I see version 27.0.1, not 26.0.5

**Comment by pachulo** [comment]
How can we test this 26.0.5 version @kyrofa ?

**Comment by scubamuc** [comment]
@pachulo, I'm getting muddled up too with all the PR's.

26.05 should be in #2496, but instead we have 27.01?

27.02 is in #2499. I think that's how it should be?

**Comment by kyrofa** [comment]
@pachulo we need a new snap package defined on the 26 branch in lp. I'm getting server errors from lp this morning though, so we'll need to wait until those are resolved.

**Comment by pachulo** [comment]
OK, tested the fresh install and everything looks fine.

@scubamuc you can test this now using the `26/beta` channel

**Review by pachulo — APPROVED** [review]

**Comment by pachulo** [comment]
I've just pushed branch 26 to LP, so `26/beta` channel should get this after some hours.

**Comment by scubamuc** [comment]
Fresh install tests completed **with** issues!

grafik
grafik

I had an issue: After entering admin user and password for initialisation the **recommended apps** installation did not automatically start and displayed an error -- **recommended apps** could not be found --. I hit refresh and **recommended apps** installation started as usual.

**Pull request merged**
