### PR TITLE
Update Nextcloud to 30.0.1

### LINKED ISSUE #2926: Update Nextcloud to 30.0.1
New point release for version 30 released.

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #2926

### CODE REVIEW

**Comment by stondino00** [comment]
Seeing this on upgrade from dev/beta snap.

image

image

**Comment by scubamuc** [comment]
@stondino00 
```bash
sudo nextcloud.occ maintenance:mimetype:update-js
```

**Comment by scubamuc** [comment]
fresh install tests completed without issues
grafik
grafik
Error message confirmed
grafik
grafik
grafik


logs show error

**Comment by scubamuc** [comment]
grafik

**Comment by pachulo** [comment]
Does any of you have any idea of what that error with the integrity check might be related with? 🤔

**Comment by Pilzinsel64** [comment]
Please post the content of the file you get when clicking to "List of invalid files", I have an idea and need confirmation. xD I am going to work now and can't test until Sunday or Monday probably.

**Comment by Pilzinsel64** [comment]
My itention is that this file is absolutely inimportant. But why this only happens not for all people I really wonder. It's even not only on fresh install but also on upgrades from 30.0.0.

My both public prod instances with manual setup haven't this issue.

Haven't found another issue, so let's follow this: https://help.nextcloud.com/t/file-missing-reuse-dep5-file-integrity/207079

**Review by Pilzinsel64 — APPROVED** [review]
Works fine on my private prod without any issues.

I think we can merge this for now to allow beta-testers to test this. In between I'm trying to contact some Nextcloud devs and ask for this issue. https://cloud.nextcloud.com/call/xs25tz5y#message_3296336

**Comment by pachulo** [comment]
What would you do here @kyrofa ?

**Comment by Pilzinsel64** [comment]
Alright, as of this comment, we will not have an license issue, so we could merge and even release a snap package. Of course, a red error is not cool for the end-user, so I would only merge (so it's available as beta) but not release yet.

It's probably our build system that treads files beginning with an dot as invisible file/folder and ignores it. But without a deeper look into the whole build script this is just a guess.

**Comment by kyrofa** [comment]
I think @Pilzinsel64 is spot on here. Check out the part of the snapcraft.yaml that takes care of this:

https://github.com/nextcloud-snap/nextcloud-snap/blob/master/snap/snapcraft.yaml#L186-L189

Note how we have to have specific organize rules for hidden files. Let's try adding another one for .reuse.

**Review by pachulo — APPROVED** [review]

**Pull request merged**
