### PR TITLE
Nextcloud 24.0.1

### LINKED ISSUE #2076: Nextcloud 24.0.1
Bugfix point release of version 24 being released today.

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #2076

### CODE REVIEW

**Comment by Pilzinsel64** [comment]
Hi. Can I just test this by switching the channel to like "latest/pr/2077"? (Forgot the right naming) So I can give my five cents and approve the changes. Want to help and bring this forward a bit. ^^

**Review by Fran6nd — APPROVED** [review]
For me everything seems good. I do not know why GitHub sees conflicts here. Maybe missing a rebase?

**Comment by kyrofa** [comment]
Alright, builds of this PR for all architectures are available in the `latest/beta/pr-2077` channel.

**Comment by Pilzinsel64** [comment]
I've tried to refresh on provided channel but it seems there went something wrong. It aborted with an error as you can see in the screenshot. Without doing anything after: I can access the web page as normal. I'm on Version 23.0.5.
grafik

**Comment by kyrofa** [comment]
Oh darn, right I need to rebuild this again, then that'll work.

**Comment by kyrofa** [comment]
Alright done, try again.

**Comment by Pilzinsel64** [comment]
Aright, I tried to refresh again.

The Update has finished without problems and everything seems to work as normal, as of now. Good work! ♥
If I get any abnormalities I will edit this comment here below the screenshots. ^^

grafik
grafik


Btw...
> Oh darn, right thank you-- the version number on stable is technically later than the previous build because I forgot to merge master back into develop. I need to rebuild this again, then that'll work.

No problem, that's normal! Things like this happens to me all the time. :D

**Comment by stondino00** [comment]
I've had 0 issues with this in testing.

**Review by kyrofa — APPROVED** [review]
This works well for me, both on a fresh install and an upgrade.

**Comment by pachulo** [comment]
Hi @kyrofa ! Can we get a `23` branch then?
Thanks!

**Comment by kyrofa** [comment]
Yessir, done.

**Pull request merged**
