### PR TITLE
Release 27.1.4snap1

### LINKED ISSUE #2616: Upgrade Nextcloud to 27.1.4
Should be released sometime today.  This is a placeholder for that release.

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Fix #2616 

27.1.5 comming in a week, so maybe we should release this before. It's long enough in beta anyway imo. :)

### CODE REVIEW

**Review by pachulo — APPROVED** [review]

**Comment by Pilzinsel64** [comment]
@pachulo You or @kyrofa would need to merge and tag this. I am not allowed to.

**Comment by pachulo** [comment]
@kyrofa & @Pilzinsel64 could it be that you forgot to sync master and develop when releasing this? https://github.com/nextcloud-snap/nextcloud-snap/compare/develop...master

**Comment by Pilzinsel64** [comment]
Oh, looks like. Not sure how that's beeing done? Just rebase develop on master?

**Comment by kyrofa** [comment]
@pachulo yessir, good catch. Just fixed.

**Pull request merged**
