### PR TITLE
Upgrade Nextcloud 22.1.1

### LINKED ISSUE #1813: Upgrade: Nextcloud 22.1.1
The first patch for Nextcloud 22 has been released recently and works well for my two instances. I would say, there is nothing in the way anymore for the Snap to get the update. What do you think?

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #1813

### CODE REVIEW

**Comment by kyrofa** [comment]
@stondino00 some conflicts here, mind rebasing?

**Comment by kyrofa** [comment]
Alright, builds have been published for all architectures into `latest/beta/pr-1814`, please give it a test!

**Review by kyrofa — APPROVED** [review]
This seems to work well in my testing. I'll let @pachulo merge assuming he agrees.

**Comment by pachulo** [comment]
Hi! I'm sorry, but I won't be able to test this until the weekend...

**Comment by pachulo** [comment]
OK, I did test a new install of this and everything looks solid. I think that we can move on once integration tests has passed @kyrofa !

**Pull request merged**
