### PR TITLE
Upgrade MySQL to 8.0.30

### LINKED ISSUE #2141: Upgrade MySQL 8.0.30
Contains security fixes.

https://www.oracle.com/security-alerts/cpujul2022.html#AppendixMSQL

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #2141

### CODE REVIEW

**Comment by stondino00** [comment]
Hey @kyrofa, when your free can we merge this?  Thanks

**Comment by kyrofa** [comment]
Thanks for the ping @stondino00, not sure how I missed this one!

**Review by kyrofa — APPROVED** [review]

**Comment by stondino00** [comment]
I'm not showing the 8.0.30 mysql being updated following the beta channel.  I show it being bult on the launchpad site with 8.0.30 mysql but when I check for updates, it only shows the 24.0.3snap1

image

**Comment by kyrofa** [comment]
Oh whoops, because I closed it on accident :man_facepalming:

**Comment by stondino00** [comment]
Ok cool.  No worries sir.  Thought I may be missing something so was a bit scared to ask lol.  Thanks

**Pull request merged**
