### PR TITLE
Release 28.0.5snap1

### LINKED ISSUE #2641: Update Nextcloud to 28
### Pending todos
- [x] Wait for 28.0.4 stable
- [x] https://github.com/nextcloud-snap/nextcloud-snap/pull/2665
- [x] Create branch `27`
- [x] Create label `27`

### Pending PRs
- [x] ~~https://github.com/nextcloud-snap/nextcloud-snap/pull/2657~~
- [x] https://github.com/nextcloud-snap/nextcloud-snap/pull/2655
- [x] https://github.com/nextcloud-snap/nextcloud-snap/pull/2659

### Pending upstream issues
- [x] https://github.com/nextcloud/server/issues/42286
- [x] https://github.com/nextcloud/server/issues/42671

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Fix #2641 
See: https://github.com/nextcloud-snap/nextcloud-snap/issues/2641#issuecomment-2084617746

### CODE REVIEW

**Review by scubamuc — APPROVED** [review]

**Comment by scubamuc** [comment]
Fresh install tests completed with issues

grafik

grafik

grafik

1. Maintenance window: `sudo nextcloud.occ config:system:set maintenance_window_start --value="1"`
2. Missing indices: `sudo nextcloud.occ db:add-missing-indices`

logs look fine

**Comment by scubamuc** [comment]
CODE & Nextcloud Office test:
grafik
no issues

**Comment by Pilzinsel64** [comment]
1. To be ignored. See https://github.com/nextcloud-snap/nextcloud-snap/issues/2641#issuecomment-2084617746
2. Didn't that happen to the [most recent 27 update](https://github.com/nextcloud-snap/nextcloud-snap/pull/2728#issuecomment-2078832262) too? The occ command seems to work like before, but why doesn't get it executed anymore? 🤔

**Comment by scubamuc** [comment]
retested fresh install `sudo snap install nextcloud --channel=latest/beta/pr-2731`

wait 15 Minutes...

issues persist, see messages;

grafik

**Comment by Pilzinsel64** [comment]
Oh dear, I didn't installed recommended apps. That's why. When you install mail, you get a bunch of missing indices. This seems to be a bug(?) by the Mail app. The most users will not regonize that as bug as it is common that indices are missing after an update (or for snap users: missing indices always get fixed on update). The only way you get this is installing the Mail app without having it installed every before.

This PR probably introduces the behavior: https://github.com/nextcloud/mail/pull/9295
Looks like it's time for me to create a new upstream issue. :/

But: Mail app is not installed by default -> we don't support it officially -> mail works with missing indices -> no problem for us

**Comment by scubamuc** [comment]
@Pilzinsel64,
>But as mail isn't installed by default, this shouldn't be a blocker for us...

my tests are done as an absolute noob would install the snap. the process hasn't changed. that would definitely include installing "recommended apps". so the "mail app" will most probably be installed when the snap is initialised. there is a wiki entry describing how to add indices... so that's covered.

I'm not sure if this is a PR-Testing issue because according to this;

grafik

your hint "should be done by fixer" is absolutely right. how will we know? @kyrofa could you shed some light please?

**Comment by Pilzinsel64** [comment]
Closing as we wait for #2738 and #2659

**Pull request closed without merging**
