### PR TITLE
snapcraft.yaml: remove mdns-publisher

### PR DESCRIPTION
**Pull request by pachulo**
Also remove mentions of mDNS in README

### CODE REVIEW

**Review by Pilzinsel64 — APPROVED** [review]

**Review by scubamuc — APPROVED** [review]

**Comment by Pilzinsel64** [comment]
@pachulo I hope you're allowed to merge. Otherwise you may combine the two PRs? Bad situation if a PR needs each other to be merged. :D

**Comment by kyrofa** [comment]
I gotcha, guys.

**Comment by scubamuc** [comment]
Hey guys, I think you've missed the [issue debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script) see here #2518

**Comment by Pilzinsel64** [comment]
> Hey guys, I think you've missed the [issue debugging script](https://github.com/nextcloud-snap/nextcloud-snap/wiki/Issue-Debugging-Scripts#debugging-script) see here #2518

Goog catch. Just removed it from the wiki page. No more PR needed.:)

**Comment by kyrofa** [comment]
Thanks guys, good catch indeed, I forgot all about that.

**Pull request merged**
