### PR TITLE
Update MySQL to 8.0.37

### LINKED ISSUE #2732: Update MySQL to 8.0.37
Oracle Q2 Security Release

https://www.oracle.com/security-alerts/cpuapr2024.html#AppendixMSQL

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #2732

### CODE REVIEW

**Review by scubamuc — APPROVED** [review]

**Comment by stondino00** [comment]
@kyrofa looks like this is needing an updated cmake version?

image

**Comment by pachulo** [comment]
> @kyrofa looks like this is needing an updated cmake version?

Ubuntu 18.04 ships [version 3.10.2](https://launchpad.net/ubuntu/bionic/+source/cmake), so yet another reason to upgrade to, at least, core20... 🤕 

By the way, [snapcraft developers confirmed that there are no plans to re-introduce local plugins](https://forum.snapcraft.io/t/local-v2-plugin-base-core22/32227/13), but I don't really know which of the alternatives is better for our use case...

**Comment by kyrofa** [comment]
Oh, lovely. I'm afraid I'm not going to be much help with the core20 upgrade, the new snapcraft is completely foreign to me. I hope one of the other @nextcloud-snap/developers has more experience with it?

**Comment by pachulo** [comment]
> I hope one of the other @nextcloud-snap/developers has more experience with it?

I'm sorry, but I don't have any experience with it.
Maybe we can ask for help/advice on one of those [starcraft clinic sessions they do](https://forum.snapcraft.io/t/starcraft-clinic-2024-apr-26/39873)?

**Comment by stondino00** [comment]
Appears I have a workaround to get the latest mysql 8.0.37 to build with minimal amount of adjustments in this pr #2735.  Probably not the most elegant way of accomplishing this but it uses the cmake snap to build the latest mysql and my system upgraded to this PR just fine and is showing the latest version of mysql.

**Comment by stondino00** [comment]
Bundled in PR #2735

**Pull request closed without merging**
