### PR TITLE
Upgrade Nextcloud to 22.2.3

### LINKED ISSUE #1927: Upgrade Nextcloud to 22.2.3
Being released soon.

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #1927

### CODE REVIEW

**Comment by stondino00** [comment]
Tracking a regression that makes 22 very slow apparently that was merged into 22.2.1.  Hoping they release 22.2.2 soon.

https://github.com/nextcloud/server/issues/29678

**Review by AndreGeddert — APPROVED** [review]
URI and sha256sum ok

**Review by AndreGeddert — DISMISSED** [review]
URI and sha256sum ok

**Comment by stondino00** [comment]
Hey @kyrofa, when your free, can you see what's up with this 22.2.3 build?  Thanks

**Comment by kyrofa** [comment]
Circle claims that it ran too long. Either it was a fluke (I've re-run it) or they changed how their quota works. I really hope it's the former, because it takes a long time to build this thing.

**Comment by stondino00** [comment]
> Circle claims that it ran too long. Either it was a fluke (I've re-run it) or they changed how their quota works. I really hope it's the former, because it takes a long time to build this thing.

Sounds great.  Thanks sir!

**Comment by stondino00** [comment]
> Circle claims that it ran too long. Either it was a fluke (I've re-run it) or they changed how their quota works. I really hope it's the former, because it takes a long time to build this thing.

Well shoot!  Looks like this is going to be a bigger set back for getting this moved to devel.

**Comment by kyrofa** [comment]
Oof, all of our CI runs are failing now, this must have changed over last night or something. I'm not quite sure what to do about this.

**Comment by stondino00** [comment]
I've submitted a support request with circleci but may take a few days.  Not sure if you could get a response quicker.  I guess possibly try again since there was an outage on the google platform earlier today and see if they complete this time.  Not sure.

**Comment by stondino00** [comment]
So seems like maybe they changed something to not allow builds as long as these take.  Others have taken 2-3 hours to build and those were fine but everything is being stopped just after an hour.

**Comment by kyrofa** [comment]
Yeah exactly. I guess it's time to find a new CI system.

**Comment by pachulo** [comment]
@kyrofa I propose another option for the short term: when I was checking yesterday, the CircleCI's plan that would fit our use case was 45$/month.
I'm willing to pay for this month and then we can go find another CI.

**Comment by kyrofa** [comment]
That's tremendously generous of you, @pachulo! However, there is something within me that looks upon this as some sort of extortion and I refuse to give in to it :stuck_out_tongue: . I think we'll find a better solution in #1939.

**Comment by stondino00** [comment]
Hey @kyrofa,

I got this back from CircleCi support.  Apparently we can specify a larger resource allocation and see if our builds finish faster that way.

If you would like to continue using the free plan we would recommend changing your resource class to large class is available on the free plan and will give you access to more resources which will help reduce the duration, thanks to additional CPU and memory.

More information can be found here: https://circleci.com/docs/2.0/executor-types/#available-docker-resource-classes

This can be done by adding: resource_class: large and example of this can be seen below:

Current:

    docker:
      - image: ubuntu:bionic
Proposed:

    docker:
      - image: ubuntu:bionic
    resource_class: large

**Comment by kyrofa** [comment]
Alright CI has been fixed, I took the liberty of updating this branch.

**Comment by kyrofa** [comment]
Thank you for looking into that, @stondino00. Given how long it was taking (and how long it takes on my own beefy machines) I don't think we'll be able to duck under an hour. CircleCI is out. I took the liberty of updating this branch to get new tests running.

**Pull request merged**
