### PR TITLE
Update Nextcloud to 29.0.1

### LINKED ISSUE #2750: Update Nextcloud to 29.0.1
https://nextcloud.com/changelog/#latest29

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #2750

### CODE REVIEW

**Review by scubamuc — APPROVED** [review]

**Comment by scubamuc** [comment]
fresh install tests completed with issues

`sudo snap install nextcloud --channel=latest/beta/pr-2751` 

grafik
grafik

grafik

**Comment by Pilzinsel64** [comment]
Waiting for #2641 to be resolved.

**Review by Pilzinsel64 — APPROVED** [review]
Rebased. Auto-merge will happen when test successed. Let's see how many things break time. :D

Will update my private prod not until Thursday morning as I'm not at home and very busy tomorrow. But then, as always, I will test bit around and see if there is any new issue now. JFYI.

One thing I wonder the the `caldav not probable configured` from @scubamuc first test. But let's see. I haven't had this error on other manual installed insetances with NC29 yet.

**Comment by scubamuc** [comment]
@Pilzinsel64,

>One thing I wonder the the caldav not probable configured from @scubamuc first test. But let's see. I haven't had this error on other manual installed insetances with NC29 yet.

I haven't seen this before either and nothing has changed same r-proxy. same machine, same tests, same script...

**Comment by Pilzinsel64** [comment]
@scubamuc Yea, let's see. Seems that they have changed how the check itself is performed by using php on the server instead of your local browser (and maybe something else). I already found several possible reasons in an [upstream issue](https://github.com/nextcloud/server/issues/45033). Going to troubleshoot this and find the real issue + fix for us on Thursday.

**Comment by scubamuc** [comment]
fresh install tests completed without issues

grafik

grafik

https://github.com/nextcloud/server/issues/45033#issuecomment-2136532798
confirming  documentation, reverse proxy settings #2757

grafik

Logs loo fine

**Pull request merged**
