### PR TITLE
snapcraft: use branch 7.x

### LINKED ISSUE #2122: Incompatible with snapcraft v7
Snapcraft v7 ripped out APIs we are using in our plugins (no deprecation notices or anything). As a result, the Nextcloud snap doesn't build with snapcraft v7. See [here](https://forum.snapcraft.io/t/snapcraft-7-refuses-to-build-core18-snap/30592?u=kyrofa) for more information.

We need to rewrite our plugins to work with snapcraft v7.

### PR DESCRIPTION
**Pull request by pachulo**
The bug that was hitting us has been solved in 7.5.3: https://github.com/snapcore/snapcraft/issues/4285

We have to stick with 7.x, as 8.x will deprecate `core18` snaps.

If this works, we will need to update snap building options on Launchpad too.

Fixes #2122

### CODE REVIEW

**Review by scubamuc — APPROVED** [review]

**Review by Pilzinsel64 — APPROVED** [review]

**Comment by pachulo** [comment]
Should we merge this @kyrofa ?

**Review by kyrofa — APPROVED** [review]
Awesome! We'll need to update our launchpad snap configurations to make sure we're using 7.x instead of 6.x as well.

**Comment by pachulo** [comment]
I've already updated most of the active snap configurations, but those are still on your personal user:
* https://launchpad.net/~kyrofa/+snap/nextcloud-daily-27
* https://launchpad.net/~kyrofa/+snap/nextcloud-daily-26
* https://launchpad.net/~kyrofa/+snap/nextcloud-daily-25

So I cannot update them.

By the way, should we clean old versions snap configs?

**Comment by kyrofa** [comment]
Alright I updated those as well as changed their ownership.

> By the way, should we clean old versions snap configs?

I'm not following. What do you mean?

**Comment by pachulo** [comment]
> I'm not following. What do you mean?

In [here](https://launchpad.net/~nextcloud-snap-dev/+snaps) I see a lot of "snap packages" that we won't be using anymore. For example:
* https://launchpad.net/~kyrofa/+snap/nextcloud-21
* https://launchpad.net/~kyrofa/+snap/nextcloud-daily-21
* https://launchpad.net/~kyrofa/+snap/nextcloud-20
* https://launchpad.net/~kyrofa/+snap/nextcloud-daily-20

And so on, so I was just guessing if it made sense to remove them.

**Comment by kyrofa** [comment]
Nah, they're not doing any harm.

**Pull request merged**
