### PR TITLE
Upgrade Nextcloud to 26.0.2

### LINKED ISSUE #2391: Upgrade Nextcloud to 26
~~Download: https://download.nextcloud.com/server/releases/nextcloud-26.0.1.tar.bz2
Checksum: `6f9c6a1248d7c8af4ad473d73a42565f6adabad4531c5cfa57bc3497b2b64f48`~~

@kyrofa ~~It's not on changelog yet~~ but update is rolled out. Should I already make a PR anyway, or do you even want to do that yourself?

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Fixes #2391 

An early PR as discussed in linked issue.

I probably missed something, just tell me then.

### CODE REVIEW

**Comment by Pilzinsel64** [comment]
Closing due https://github.com/nextcloud/server/issues/37610

**Comment by Pilzinsel64** [comment]
Re-open as discussed in #2391

**Comment by Pilzinsel64** [comment]
Maybe we should make v26 available before v27 is out.

I'm using the `26/edge` for my private instance since it's available and refreshed a few times (I'm exactly on the state of v26.0.2 atm).
I had no other problems then #2365.

**Comment by Pilzinsel64** [comment]
Updated to v26.0.2 as it already is on the changelog page and works fine for me.

**Comment by Pilzinsel64** [comment]
I really suggest to at merge an update to NC26 to start pushing to `26/beta` and then to `26/stable`. The tests do success and I'm using the `26/edge` channel since the release of NC26 without any problems. I know that it's only my system, but that is the only what I can do from my side, I guess.

NC27 is on the timeline for middle of march, an issue for enabling dailies is done here: #2420 

We probably should get NC26 snap stable before end of July, so people can safely update until NC27 snap stable will be availabel too.

-----

**Off topic - DM to @kyrofa**
Normally I avoid pinging you as I know you have a busy real-life. But you maybe should consider to involve someone you trust as co-dev with write access for the case where you self haven't the time for, so things can keep up-to-date and you maybe don't have pressure to do it yourself. Just a very friedly suggestion, absolutely no attack! ;=)

**Review by scubamuc — APPROVED** [review]
Go

**Review by kyrofa — APPROVED** [review]

**Comment by abdusalamApps** [comment]
Any news on when this is gonna be released?

**Comment by Pilzinsel64** [comment]
@abdusalamApps It's in beta at the moment. ~1 week until it moves to stable.

**Comment by pachulo** [comment]
Should I create the `25` branch on the repo now @kyrofa ?

**Comment by kyrofa** [comment]
Oh, right. Yes please, starting right before this merge.

**Pull request merged**
