### PR TITLE
Release 29.0.7snap1

### PR DESCRIPTION
**Pull request by pachulo**

### CODE REVIEW

**Review by scubamuc — APPROVED** [review]

**Comment by scubamuc** [comment]
@pachulo calls for fresh install retest?

**Comment by pachulo** [comment]
> @pachulo calls for fresh install retest?

They shouldn't be necessary; I'm more interested in knowing if you are running the release on the `latest/beta` channel on production.

**Comment by scubamuc** [comment]
@pachulo 
>  if you are running the release on the latest/beta channel on production.

nope not on production. could give you access to a fresh install though?
need access? i can fire up the instance and grant access.

**Comment by pachulo** [comment]
> nope not on production. could give you access to a fresh install though?
need access? i can fire up the instance and grant access.

Thanks, that's not needed. Fresh installs were already covered by your tests on the PRs.

My prod instance is on the 28 track, so somebody from @nextcloud-snap/developers should try to upgrade to this release (using `latest/beta`) on a production instance and then check that everything is fine after a few days.

**Comment by scubamuc** [comment]
@Pilzinsel64 you have 29.0.7 running on production? https://github.com/nextcloud-snap/nextcloud-snap/issues/2879#issuecomment-2351393224

**Review by Pilzinsel64 — APPROVED** [review]
Running on my private prod without issues.

**Pull request merged**
