### PR TITLE
Update Nextcloud to 27.1.5

### LINKED ISSUE #2630: Update Nextcloud to 27.1.5
What's Changed

    [stable27] fix: lower threshold for system address book sync by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/41671
    [stable27] fix: Also cleanup orphaned shares user cannot be found anymore by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/41643
    [stable27] fix(dav): Avoid date diffing if PHP is buggy by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/41730
    [stable27] fix: Avoid triggering a defered sidebar open if openFile is already handling that by @juliushaertl in https://github.com/nextcloud/server/pull/41636
    [stable27] fix(scheduling): don't send iMIP emails to rooms / resources by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/41315
    [stable27] fix(files_sharing): fix sharing tab translations by @Fenn-CS in https://github.com/nextcloud/server/pull/41736
    [stable27] reuse sharing disabled state when listing folder content by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/41462
    [stable27] do not write htaccess file if disk space is too low by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/41608
    [stable27] fix(files_versions): Check for user and owner before call getUserFolder by @solracsf in https://github.com/nextcloud/server/pull/41786
    fix(ui): Do not close all menus on right click by @ChristophWurst in https://github.com/nextcloud/server/pull/41812
    Nextcloud 27 : Replace "Update" with "Edit" in share dialog by @Jerome-Herbinet in https://github.com/nextcloud/server/pull/41734
    [stable27] Improve share logic for enforced password & expiry date by @Fenn-CS in https://github.com/nextcloud/server/pull/41936
    [stable27] fix(TemplateManager): Bail early if templatedirectory is empty by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/42002
    [stable27] Fix/text processing types covariant stable27 by @marcelklehr in https://github.com/nextcloud/server/pull/41997
    fix(security): Update expiration date in security.txt by @nickvergessen in https://github.com/nextcloud/server/pull/42004
    [stable27] Serve .flac audio files by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/41557
    [stable27] fix: Fix linkToOCSRouteAbsolute() without index.php and with subfolder by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/41626
    [stable27] fix: Delete ghost versions of non-existing files by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/41296
    [stable27] fix: Show error message when CSRF check fails at login by @ChristophWurst in https://github.com/nextcloud/server/pull/41970
    [stable27] feat(LDAP): implement IIsAdmin interface by @blizzz in https://github.com/nextcloud/server/pull/41813
    fix: Update @nextcloud/dialogs to 4.2.2 to fix translations of FilePicker by @susnux in https://github.com/nextcloud/server/pull/42034
    [stable27] fix(backupcodes): Remove old notifications before creating a new remi… by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/41451
    [stable27] Fix root mounts not being setup in some cases by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/41090
    [stable27] fix(systemreport): Mask onlyoffice secret as sensitive by @nickvergessen in https://github.com/nextcloud/server/pull/42081
    [stable27] fix: Properly fetch version from shared files by accessing the owner storage version by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/42075
    [stable27] fix(updatecheck): Don't wait 120s for a response of updater.nextcloud… by @nickvergessen in https://github.com/nextcloud/server/pull/42078
    [stable27] fix(bruteforce-protection): Don't throw a 500 when MaxDelayReached is… by @nickvergessen in https://github.com/nextcloud/server/pull/42083
    [stable27] fix(security): Handle idn_to_utf8 returning false by @nickvergessen in https://github.com/nextcloud/server/pull/42085
    [stable27] Fix AppSettingsController.php overwriting currentLanguage by @solracsf in https://github.com/nextcloud/server/pull/42063
    fix(dist): assets were not compiled by @blizzz in https://github.com/nextcloud/server/pull/42091
    27.1.5 RC1 by @blizzz in https://github.com/nextcloud/server/pull/42015
    [stable27] fix(security): Update CA certificate bundle by @nextcloud-command in https://github.com/nextcloud/server/pull/42188
    27.1.5 by @blizzz in https://github.com/nextcloud/server/pull/42147

### PR DESCRIPTION
**Pull request by stondino00**
Fixes #2630

### CODE REVIEW

**Comment by Pilzinsel64** [comment]
The tests do fail at the same point then the daily tests. But only for NC27+. Not sure yet what the cause is. But this line sounds interesting:
```
In Setup.php line 568:
                                                                               
  /snap/nextcloud/x1/htdocs does not have enough space for writing the htacce  
  ss file! Not writing it back!      
```

**Comment by stondino00** [comment]
We may need @kyrofa to help on this one.  Not sure either.

**Comment by kyrofa** [comment]
I suspect that the manual installation in these newer versions require read-access to the htdocs directory because it wants to write an htaccess file. The current version doesn't do that. We need to look into that, see if there's a way to opt out of that behavior.

**Comment by Pilzinsel64** [comment]
I opened an issue on the server repo. Let's see if we get a feedback for this. https://github.com/nextcloud/server/issues/42286

To be honest, I didn't find the commit that added that behavior. That are just to many commits there. :/

**Comment by Pilzinsel64** [comment]
> I suppose I'm the only one that received notifications of those failures, huh. I should figure out a way to change that.

I did see it yesterday when I was looking for why the `28/edge` builds aren't up. But I didn't bother as the tests for the PR I updated yesterday successed. I assumed that's just a temporary issue, sorry. :/

**Comment by stondino00** [comment]
Wonder if we are hitting this commit.  This is new in 28 and 27.1.5

[stable27] do not write htaccess file if disk space is too low by @backportbot-nextcloud in https://github.com/nextcloud/server/pull/41608

**Comment by Pilzinsel64** [comment]
@kyrofa Can you say anything regarding the available disk space for the tests on GitHub? Each nc release has a slightly increased size, maybe we just reached the disk limit?

**Comment by kyrofa** [comment]
Actually no, I think @stondino00 is spot on: the snap is a squashfs image, it's literally by definition 100% full. The available disk space on the host doesn't really matter here.

**Comment by pachulo** [comment]
Hey folks, do you think it makes sense to push 27.1.4 to the stable channel in the meantime?

**Comment by kyrofa** [comment]
Yes, I just haven't verified it yet, have you?

**Comment by pachulo** [comment]
I've just tested a fresh install and everything seems fine.

**Comment by Pilzinsel64** [comment]
An upgrade also works fine, tested on my prod.

**Comment by scubamuc** [comment]
fresh install tests [completed an documented here](https://github.com/nextcloud-snap/nextcloud-snap/pull/2617#issuecomment-1824868131)

should I run these again?

**Comment by pachulo** [comment]
OK, [in here they say that the latest updates solve some security issues](https://nextcloud.com/blog/december-2023-minor-releases-hub-4-6/), and they also now disclosed 2 moderate security issues that were solved in 27.1.4:
1. https://github.com/nextcloud/security-advisories/security/advisories/GHSA-3f8p-6qww-2prr
2. https://github.com/nextcloud/security-advisories/security/advisories/GHSA-5j2p-q736-hw98

So, how should we proceed @kyrofa ?

**Comment by kyrofa** [comment]
27.1.4 is in stable, now. Regarding 27.1.5, our only real option is to wait for a fix.

**Comment by Pilzinsel64** [comment]
Closing as we need to wait for 27.1.6 at least.

**Pull request closed without merging**
