### PR TITLE
release 27.1.2snap1

### PR DESCRIPTION
**Pull request by pachulo**

### CODE REVIEW

**Review by scubamuc — APPROVED** [review]

**Comment by Pilzinsel64** [comment]
Hm, not sure but don't you need to target master instead of develop? 🤔

**Comment by pachulo** [comment]
You're totally right @Pilzinsel64 , thanks for the hint!

**Comment by pachulo** [comment]
By the way @kyrofa , when do you want to push this to `latest/stable`?

**Comment by scubamuc** [comment]
@pachulo & @kyrofa , this is not in latest/stable yet? we're still sitting on 27.1.1

**Pull request merged**
